# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.service_binding_api import ServiceBindingApi


class TestServiceBindingApi(unittest.TestCase):
    """ServiceBindingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceBindingApi()

    def tearDown(self) -> None:
        pass

    def test_api_service_bindings_get_collection(self) -> None:
        """Test case for api_service_bindings_get_collection

        Retrieves the collection of ServiceBinding resources.
        """
        pass

    def test_api_service_bindings_id_delete(self) -> None:
        """Test case for api_service_bindings_id_delete

        Removes the ServiceBinding resource.
        """
        pass

    def test_api_service_bindings_id_get(self) -> None:
        """Test case for api_service_bindings_id_get

        Retrieves a ServiceBinding resource.
        """
        pass

    def test_api_service_bindings_post(self) -> None:
        """Test case for api_service_bindings_post

        Creates a ServiceBinding resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
