# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.deployment_api import DeploymentApi


class TestDeploymentApi(unittest.TestCase):
    """DeploymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentApi()

    def tearDown(self) -> None:
        pass

    def test_api_deployments_get_collection(self) -> None:
        """Test case for api_deployments_get_collection

        Retrieves the collection of Deployment resources.
        """
        pass

    def test_api_deployments_id_delete(self) -> None:
        """Test case for api_deployments_id_delete

        Removes the Deployment resource.
        """
        pass

    def test_api_deployments_id_get(self) -> None:
        """Test case for api_deployments_id_get

        Retrieves a Deployment resource.
        """
        pass

    def test_api_deployments_id_patch(self) -> None:
        """Test case for api_deployments_id_patch

        Updates the Deployment resource.
        """
        pass

    def test_api_deployments_post(self) -> None:
        """Test case for api_deployments_post

        Creates a Deployment resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
