# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.credit_transaction import CreditTransaction

class TestCreditTransaction(unittest.TestCase):
    """CreditTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditTransaction:
        """Test CreditTransaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditTransaction`
        """
        model = CreditTransaction()
        if include_optional:
            return CreditTransaction(
                organization = 'https://example.com/',
                type = 'top_up',
                status = 'pending',
                amount_cents = 56,
                currency = 'usd',
                stripe_checkout_session_id = '',
                usage_hour = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                resource_kind = 'compute',
                usage_seconds = 56,
                unresolved_containers = 56,
                usage_bytes = None,
                engine_millis = None,
                usage_rows = 56,
                stripe_event_id = '',
                created_by = someones_computer_sdk.models.user.User(
                    id = '', 
                    username = '', 
                    display_name = '', ),
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CreditTransaction(
        )
        """

    def testCreditTransaction(self):
        """Test CreditTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
