# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.deployment_access_gate_api import DeploymentAccessGateApi


class TestDeploymentAccessGateApi(unittest.TestCase):
    """DeploymentAccessGateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentAccessGateApi()

    def tearDown(self) -> None:
        pass

    def test_deployment_access_gates_create(self) -> None:
        """Test case for deployment_access_gates_create

        Creates a DeploymentAccessGate resource.
        """
        pass

    def test_deployment_access_gates_delete(self) -> None:
        """Test case for deployment_access_gates_delete

        Removes the DeploymentAccessGate resource.
        """
        pass

    def test_deployment_access_gates_get(self) -> None:
        """Test case for deployment_access_gates_get

        Retrieves a DeploymentAccessGate resource.
        """
        pass

    def test_deployment_access_gates_list(self) -> None:
        """Test case for deployment_access_gates_list

        Retrieves the collection of DeploymentAccessGate resources.
        """
        pass

    def test_deployment_access_gates_update(self) -> None:
        """Test case for deployment_access_gates_update

        Updates the DeploymentAccessGate resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
