# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.swarm_api import SwarmApi


class TestSwarmApi(unittest.TestCase):
    """SwarmApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SwarmApi()

    def tearDown(self) -> None:
        pass

    def test_api_swarms_get_collection(self) -> None:
        """Test case for api_swarms_get_collection

        Retrieves the collection of Swarm resources.
        """
        pass

    def test_api_swarms_id_delete(self) -> None:
        """Test case for api_swarms_id_delete

        Removes the Swarm resource.
        """
        pass

    def test_api_swarms_id_get(self) -> None:
        """Test case for api_swarms_id_get

        Retrieves a Swarm resource.
        """
        pass

    def test_api_swarms_id_patch(self) -> None:
        """Test case for api_swarms_id_patch

        Updates the Swarm resource.
        """
        pass

    def test_api_swarms_post(self) -> None:
        """Test case for api_swarms_post

        Creates a Swarm resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
