# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.o_auth_identity import OAuthIdentity

class TestOAuthIdentity(unittest.TestCase):
    """OAuthIdentity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuthIdentity:
        """Test OAuthIdentity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuthIdentity`
        """
        model = OAuthIdentity()
        if include_optional:
            return OAuthIdentity(
                provider = 'github',
                provider_user_id = '',
                user = someones_computer_sdk.models.user.User(
                    email = '', 
                    username = '', 
                    display_name = '', 
                    theme = 'house', 
                    locale = 'en_GB', 
                    timezone = '', 
                    password = '', 
                    ldap_dn = '', 
                    avatar_photo = someones_computer_sdk.models.user_avatar_photo.UserAvatarPhoto(
                        photo = '', 
                        type = '', 
                        id = '', ), 
                    roles = [
                        ''
                        ], 
                    disabled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    spam_marked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    spam_marked_by = someones_computer_sdk.models.user.User(
                        email = '', 
                        username = '', 
                        display_name = '', 
                        theme = 'house', 
                        locale = 'en_GB', 
                        timezone = '', 
                        password = '', 
                        ldap_dn = '', 
                        disabled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        spam_marked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        approved_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        email_confirmed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        credit_granted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tier_pin = 'untrusted', 
                        tier_pinned_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tier_pinned_by = , 
                        tier_pin_reason = '', 
                        oauth_identities = [
                            someones_computer_sdk.models.o_auth_identity.OAuthIdentity(
                                provider = 'github', 
                                provider_user_id = '', 
                                id = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        totp_secret = '', 
                        totp_secret_key_id = '', 
                        totp_confirmed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        recovery_codes = [
                            someones_computer_sdk.models.recovery_code.RecoveryCode(
                                code_hash = '', 
                                used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                id = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                used = True, )
                            ], 
                        machine_for = 'https://example.com/', 
                        id = '', 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        display_label = '', 
                        machine = True, 
                        ldap_managed = True, 
                        avatar_photo_type = '', 
                        user_identifier = '', 
                        granted_roles = [
                            ''
                            ], 
                        disabled = True, 
                        spam = True, 
                        approved = True, 
                        email_confirmed = True, 
                        tier_pinned = True, 
                        totp_enabled = True, 
                        deleted = True, ), 
                    approved_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email_confirmed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    credit_granted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    tier_pin = 'untrusted', 
                    tier_pinned_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    tier_pinned_by = , 
                    tier_pin_reason = '', 
                    oauth_identities = [
                        someones_computer_sdk.models.o_auth_identity.OAuthIdentity(
                            provider = 'github', 
                            provider_user_id = '', 
                            id = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    totp_secret = '', 
                    totp_secret_key_id = '', 
                    totp_confirmed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    recovery_codes = [
                        someones_computer_sdk.models.recovery_code.RecoveryCode(
                            code_hash = '', 
                            used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            id = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            used = True, )
                        ], 
                    machine_for = 'https://example.com/', 
                    id = '', 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    display_label = '', 
                    machine = True, 
                    ldap_managed = True, 
                    avatar_photo_type = '', 
                    user_identifier = '', 
                    granted_roles = [
                        ''
                        ], 
                    disabled = True, 
                    spam = True, 
                    approved = True, 
                    email_confirmed = True, 
                    tier_pinned = True, 
                    totp_enabled = True, 
                    deleted = True, ),
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return OAuthIdentity(
        )
        """

    def testOAuthIdentity(self):
        """Test OAuthIdentity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
