# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.credit_transaction_api import CreditTransactionApi


class TestCreditTransactionApi(unittest.TestCase):
    """CreditTransactionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditTransactionApi()

    def tearDown(self) -> None:
        pass

    def test_api_credit_transactions_get_collection(self) -> None:
        """Test case for api_credit_transactions_get_collection

        Retrieves the collection of CreditTransaction resources.
        """
        pass

    def test_api_credit_transactions_id_get(self) -> None:
        """Test case for api_credit_transactions_id_get

        Retrieves a CreditTransaction resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
