# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.application_json_merge_patch import ApplicationJsonMergePatch

class TestApplicationJsonMergePatch(unittest.TestCase):
    """ApplicationJsonMergePatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationJsonMergePatch:
        """Test ApplicationJsonMergePatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationJsonMergePatch`
        """
        model = ApplicationJsonMergePatch()
        if include_optional:
            return ApplicationJsonMergePatch(
                organization = 'https://example.com/',
                slug = '',
                name = '',
                isolation_level = 'shared',
                service_adoption = 'off',
                access_gate = 'none',
                current_deployment = 'https://example.com/',
                first_running_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                primary_deployment_name = '',
                legacy_stack_base = '',
                icon_key = '',
                icon_source = 'uploaded',
                build_bucket = '',
                build_key_id = '',
                deployments = [
                    'https://example.com/'
                    ],
                port_allocations = [
                    someones_computer_sdk.models.port_allocation.PortAllocation(
                        swarm = 'https://example.com/', 
                        application = 'https://example.com/', 
                        deployment_name = '', 
                        service_name = '', 
                        target_port = 56, 
                        protocol = 'tcp', 
                        published_port = 56, 
                        assigned = True, 
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pool_domain = '',
                pool_label = '',
                id = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                icon = '',
                operator_chosen_icon = True,
                icon_version = '',
                deleted = True
            )
        else:
            return ApplicationJsonMergePatch(
        )
        """

    def testApplicationJsonMergePatch(self):
        """Test ApplicationJsonMergePatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
