# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.adoption_approval_api import AdoptionApprovalApi


class TestAdoptionApprovalApi(unittest.TestCase):
    """AdoptionApprovalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdoptionApprovalApi()

    def tearDown(self) -> None:
        pass

    def test_api_adoption_approvals_get_collection(self) -> None:
        """Test case for api_adoption_approvals_get_collection

        Retrieves the collection of AdoptionApproval resources.
        """
        pass

    def test_api_adoption_approvals_id_delete(self) -> None:
        """Test case for api_adoption_approvals_id_delete

        Removes the AdoptionApproval resource.
        """
        pass

    def test_api_adoption_approvals_id_get(self) -> None:
        """Test case for api_adoption_approvals_id_get

        Retrieves a AdoptionApproval resource.
        """
        pass

    def test_api_adoption_approvals_post(self) -> None:
        """Test case for api_adoption_approvals_post

        Creates a AdoptionApproval resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
