# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.deployment_access_gate import DeploymentAccessGate

class TestDeploymentAccessGate(unittest.TestCase):
    """DeploymentAccessGate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentAccessGate:
        """Test DeploymentAccessGate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentAccessGate`
        """
        model = DeploymentAccessGate()
        if include_optional:
            return DeploymentAccessGate(
                application = 'https://example.com/',
                name = '',
                access_gate = 'none',
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                access_gate_credential = someones_computer_sdk.models.sealed_secret.SealedSecret(
                    algo = '', 
                    key_id = '', 
                    nonce = '', 
                    ciphertext = '', )
            )
        else:
            return DeploymentAccessGate(
        )
        """

    def testDeploymentAccessGate(self):
        """Test DeploymentAccessGate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
