# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.bundle_context_input import BundleContextInput

class TestBundleContextInput(unittest.TestCase):
    """BundleContextInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BundleContextInput:
        """Test BundleContextInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BundleContextInput`
        """
        model = BundleContextInput()
        if include_optional:
            return BundleContextInput(
                service = '',
                context_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b',
                dockerfile = 'Dockerfile',
                additional_contexts = [
                    someones_computer_sdk.models.bundle_additional_context_input.BundleAdditionalContextInput(
                        name = '', 
                        context_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b', )
                    ]
            )
        else:
            return BundleContextInput(
                service = '',
                context_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b',
        )
        """

    def testBundleContextInput(self):
        """Test BundleContextInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
