# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.deployment_variable import DeploymentVariable

class TestDeploymentVariable(unittest.TestCase):
    """DeploymentVariable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentVariable:
        """Test DeploymentVariable
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentVariable`
        """
        model = DeploymentVariable()
        if include_optional:
            return DeploymentVariable(
                deployment = 'https://example.com/',
                variable_version = someones_computer_sdk.models.variable_version.VariableVersion(
                    variable = someones_computer_sdk.models.variable.Variable(
                        organization = 'https://example.com/', 
                        application = 'https://example.com/', 
                        key = '', 
                        sensitive = True, 
                        secret_file_delivery = True, 
                        versions = [
                            someones_computer_sdk.models.variable_version.VariableVersion(
                                version = 56, 
                                algo = '', 
                                key_id = '', 
                                nonce = '', 
                                ciphertext = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                created_by = someones_computer_sdk.models.user.User(
                                    id = '', 
                                    username = '', 
                                    display_name = '', ), 
                                id = '', 
                                encrypted = '', 
                                plaintext = '', )
                            ], 
                        id = '', 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        org_shared = True, 
                        deleted = True, ), 
                    version = 56, 
                    algo = '', 
                    key_id = '', 
                    nonce = '', 
                    ciphertext = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = someones_computer_sdk.models.user.User(
                        id = '', 
                        username = '', 
                        display_name = '', ), 
                    id = '', 
                    encrypted = '', 
                    plaintext = '', ),
                id = '',
                key = ''
            )
        else:
            return DeploymentVariable(
        )
        """

    def testDeploymentVariable(self):
        """Test DeploymentVariable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
