# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.managed_service_usage_bytes import ManagedServiceUsageBytes

class TestManagedServiceUsageBytes(unittest.TestCase):
    """ManagedServiceUsageBytes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedServiceUsageBytes:
        """Test ManagedServiceUsageBytes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedServiceUsageBytes`
        """
        model = ManagedServiceUsageBytes()
        if include_optional:
            return ManagedServiceUsageBytes(
            )
        else:
            return ManagedServiceUsageBytes(
        )
        """

    def testManagedServiceUsageBytes(self):
        """Test ManagedServiceUsageBytes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
