# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.models.swarm import Swarm

class TestSwarm(unittest.TestCase):
    """Swarm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Swarm:
        """Test Swarm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Swarm`
        """
        model = Swarm()
        if include_optional:
            return Swarm(
                owner = 'https://example.com/',
                kind = 'platform',
                name = '',
                endpoint = '',
                status = 'unreachable',
                public_host = '',
                roles = [
                    ''
                    ],
                last_seen_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                capacity = {
                    'key' : ''
                    },
                labels = {
                    'key' : ''
                    },
                ingress_installed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ingress_error = '',
                ingress_network = '',
                ingress_verified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ingress_verification_error = '',
                nodes = [
                    someones_computer_sdk.models.swarm_node.SwarmNode(
                        swarm = 'https://example.com/', 
                        node_id = '', 
                        hostname = '', 
                        state = '', 
                        capacity = {
                            'key' : ''
                            }, 
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                machines = [
                    someones_computer_sdk.models.machine.Machine(
                        instance = someones_computer_sdk.models.proxmox_instance.ProxmoxInstance(
                            name = '', 
                            endpoint = '', 
                            token_id = '', 
                            token_secret = '', 
                            verify_tls = True, 
                            public_key_pin = '', 
                            status = 'unreachable', 
                            last_seen_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            last_error = '', 
                            version = {
                                'key' : ''
                                }, 
                            template_vmid = 56, 
                            template_alpine_version = '', 
                            template_built_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            template_build_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            template_build_failures = 56, 
                            id = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            template = True, ), 
                        node = '', 
                        vmid = 56, 
                        name = '', 
                        size = 's', 
                        disk_blocks = 56, 
                        template_vmid = 56, 
                        address = '', 
                        state = 'requested', 
                        failure = '', 
                        provision_attempt = 56, 
                        provision_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        swarm = 'https://example.com/', 
                        organization = 'https://example.com/', 
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        disk_gigabytes = 56, 
                        provisioning_stale = True, )
                    ],
                deployments = [
                    'https://example.com/'
                    ],
                id = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                platform_owned = True,
                platform_provisioned = True,
                working_edge = True,
                deleted = True
            )
        else:
            return Swarm(
        )
        """

    def testSwarm(self):
        """Test Swarm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
