# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.organization_api import OrganizationApi


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationApi()

    def tearDown(self) -> None:
        pass

    def test_api_organizations_get_collection(self) -> None:
        """Test case for api_organizations_get_collection

        Retrieves the collection of Organization resources.
        """
        pass

    def test_api_organizations_id_delete(self) -> None:
        """Test case for api_organizations_id_delete

        Removes the Organization resource.
        """
        pass

    def test_api_organizations_id_get(self) -> None:
        """Test case for api_organizations_id_get

        Retrieves a Organization resource.
        """
        pass

    def test_api_organizations_id_patch(self) -> None:
        """Test case for api_organizations_id_patch

        Updates the Organization resource.
        """
        pass

    def test_api_organizations_post(self) -> None:
        """Test case for api_organizations_post

        Creates a Organization resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
