# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from someones_computer_sdk.api.application_api import ApplicationApi


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationApi()

    def tearDown(self) -> None:
        pass

    def test_applications_create(self) -> None:
        """Test case for applications_create

        Creates a Application resource.
        """
        pass

    def test_applications_delete(self) -> None:
        """Test case for applications_delete

        Removes the Application resource.
        """
        pass

    def test_applications_get(self) -> None:
        """Test case for applications_get

        Retrieves a Application resource.
        """
        pass

    def test_applications_list(self) -> None:
        """Test case for applications_list

        Retrieves the collection of Application resources.
        """
        pass

    def test_applications_update(self) -> None:
        """Test case for applications_update

        Updates the Application resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
