# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.port_allocation import PortAllocation
from someones_computer_sdk.models.sealed_secret import SealedSecret
from someones_computer_sdk.models.variable import Variable
from typing import Optional, Set
from typing_extensions import Self

class Application(BaseModel):
    """
    A deployable \"island\": one logical app, defined by a compose file, deployed as a swarm stack. Holds a pointer to the current (immutable) deployment; history lives in the deployment revisions.
    """ # noqa: E501
    organization: Optional[StrictStr] = Field(default=None, description="Re-home this application. Callers own everything the uniqueness constraint and the trust invariant elsewhere in the platform expect of a move — the entity itself only holds the pointer.")
    slug: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    isolation_level: Optional[StrictStr] = Field(default='shared', alias="isolationLevel")
    service_adoption: Optional[StrictStr] = Field(default='off', description="Whether a deploy's compose file is watched for services a managed equivalent could replace.", alias="serviceAdoption")
    access_gate: Optional[StrictStr] = Field(default='none', description="How this application's routed HTTP services are gated at the edge — `None` by default, so an application behaves exactly as it always has until an org manager opts it in ({@see AccessGateMode}).", alias="accessGate")
    current_deployment: Optional[StrictStr] = Field(default=None, description="Pointer to the currently active revision; null before the first deploy.", alias="currentDeployment")
    first_running_at: Optional[datetime] = Field(default=None, description="The first moment any revision of this application ever reached `running` — null until it has. What {@see \\App\\Service\\Teardown\\TeardownGracePeriod} measures grace-period uptime from, in place of the current revision's own `createdAt` (#1307): a revision row is stamped at bundle ingest and a fresh one is created on every `sc deploy`, so measuring off it gave a six-month-old production application a ten-minute grace period the moment it was redeployed. This is set once and never moved — a redeploy, or reactivating an old revision, does not reset it, because the application's history is what earns the longer grace, not whichever revision happens to be current.", alias="firstRunningAt")
    primary_deployment_name: Optional[StrictStr] = Field(default=None, description="Which deployment *name* owns the application's apex identity — the stack, network and hostname that carry no revision component ({@see \\App\\Service\\Placement\\StackNaming}).", alias="primaryDeploymentName")
    legacy_stack_base: Optional[StrictStr] = Field(default=None, description="The `<prefix>-<org>-<app>` join this application's stacks were **already named from**, before the separator was made unambiguous — or null, meaning nothing of this application has ever been on a swarm under the old name and {@see \\App\\Service\\Placement\\StackNaming} is free to derive the current one.", alias="legacyStackBase")
    icon_key: Optional[StrictStr] = Field(default=None, description="Object key of this application's stored icon, or null when nobody has given it one — in which case {@see \\App\\Service\\Icon\\GeneratedIcon} draws one from the name and slug, so every application has an icon either way.", alias="iconKey")
    icon_source: Optional[StrictStr] = Field(default=None, description="Where {@see $iconKey} came from — null exactly when there is no stored icon.", alias="iconSource")
    build_bucket: Optional[StrictStr] = Field(default=None, description="This application's own Garage build-context bucket — where `sc deploy`'s uploaded contexts and forwarded images are parked, and the only bucket the build key below can read. Null until the first upload provisions it ({@see \\App\\Service\\Bundle\\ApplicationBuildBucketProvisioner}); every application predating #996 looks like that too, and provisions on its next deploy.", alias="buildBucket")
    build_key_id: Optional[StrictStr] = Field(default=None, description="The access-key id of the read-only Garage key scoped to {@see $buildBucket}, handed to build tasks. Doubles as Garage's own identifier for the key (the same way {@see ManagedService::$externalKeyId} does), so nothing separate is persisted for it.", alias="buildKeyId")
    deployments: Optional[List[StrictStr]] = None
    variables: Optional[List[Variable]] = None
    port_allocations: Optional[List[PortAllocation]] = Field(default=None, alias="portAllocations")
    pool_domain: Optional[StrictStr] = Field(default=None, description="Which of the app-hosting pool domains (`snarl.dev`, `starshp.dev` — {@see \\App\\Service\\Ingress\\DomainPoolAssigner}) this application's deployments answer under, in addition to `someones.computer`. Null until its first successful deploy assigns one, and never moved after — a redeploy must resolve to the same pool hostnames it already handed out, the same reason {@see $firstRunningAt} is a latch rather than a rolling value.", alias="poolDomain")
    pool_label: Optional[StrictStr] = Field(default=None, description="Overrides the auto-slugified application name in the pool-domain hostname's `{service}.{deployment}.{label}.{poolDomain}` shape ({@see \\App\\Service\\Ingress\\PoolHostname}) — null for every application that has not opted into a custom one, which is what {@see poolLabelOrSlug()} falls back to. Unique platform-wide, the same reasoning as {@see \\App\\Entity\\Domain::$name}: two applications sharing a label would collide on the exact same DNS name the moment they also shared a deployment and service name.", alias="poolLabel")
    id: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = Field(default=None, alias="deletedAt")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    build_credential: Optional[SealedSecret] = Field(default=None, alias="buildCredential")
    access_gate_credential: Optional[SealedSecret] = Field(default=None, alias="accessGateCredential")
    icon: Optional[StrictStr] = Field(default=None, description="Point the application at a stored icon, or at none.")
    operator_chosen_icon: Optional[StrictBool] = Field(default=None, description="Whether the stored icon was chosen by a person, and so must survive the next deploy's favicon extraction.", alias="operatorChosenIcon")
    icon_version: Optional[StrictStr] = Field(default=None, description="A short, stable token for the icon a caller is looking at — the cache-busting half of the icon URL, and null when there is nothing stored to bust.", alias="iconVersion")
    deleted: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["organization", "slug", "name", "isolationLevel", "serviceAdoption", "accessGate", "currentDeployment", "firstRunningAt", "primaryDeploymentName", "legacyStackBase", "iconKey", "iconSource", "buildBucket", "buildKeyId", "deployments", "variables", "portAllocations", "poolDomain", "poolLabel", "id", "deletedAt", "createdAt", "updatedAt", "buildCredential", "accessGateCredential", "icon", "operatorChosenIcon", "iconVersion", "deleted"]

    @field_validator('isolation_level')
    def isolation_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['shared', 'dedicated']):
            raise ValueError("must be one of enum values ('shared', 'dedicated')")
        return value

    @field_validator('service_adoption')
    def service_adoption_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['off', 'auto']):
            raise ValueError("must be one of enum values ('off', 'auto')")
        return value

    @field_validator('access_gate')
    def access_gate_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'basic_auth', 'token', 'someones_auth']):
            raise ValueError("must be one of enum values ('none', 'basic_auth', 'token', 'someones_auth')")
        return value

    @field_validator('icon_source')
    def icon_source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['uploaded', 'favicon']):
            raise ValueError("must be one of enum values ('uploaded', 'favicon')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Application from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "first_running_at",
            "icon_key",
            "icon_source",
            "pool_domain",
            "id",
            "deleted_at",
            "created_at",
            "updated_at",
            "operator_chosen_icon",
            "icon_version",
            "deleted",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in variables (list)
        _items = []
        if self.variables:
            for _item_variables in self.variables:
                if _item_variables:
                    _items.append(_item_variables.to_dict())
            _dict['variables'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in port_allocations (list)
        _items = []
        if self.port_allocations:
            for _item_port_allocations in self.port_allocations:
                if _item_port_allocations:
                    _items.append(_item_port_allocations.to_dict())
            _dict['portAllocations'] = _items
        # override the default output from pydantic by calling `to_dict()` of build_credential
        if self.build_credential:
            _dict['buildCredential'] = self.build_credential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of access_gate_credential
        if self.access_gate_credential:
            _dict['accessGateCredential'] = self.access_gate_credential.to_dict()
        # set to None if current_deployment (nullable) is None
        # and model_fields_set contains the field
        if self.current_deployment is None and "current_deployment" in self.model_fields_set:
            _dict['currentDeployment'] = None

        # set to None if first_running_at (nullable) is None
        # and model_fields_set contains the field
        if self.first_running_at is None and "first_running_at" in self.model_fields_set:
            _dict['firstRunningAt'] = None

        # set to None if primary_deployment_name (nullable) is None
        # and model_fields_set contains the field
        if self.primary_deployment_name is None and "primary_deployment_name" in self.model_fields_set:
            _dict['primaryDeploymentName'] = None

        # set to None if legacy_stack_base (nullable) is None
        # and model_fields_set contains the field
        if self.legacy_stack_base is None and "legacy_stack_base" in self.model_fields_set:
            _dict['legacyStackBase'] = None

        # set to None if icon_key (nullable) is None
        # and model_fields_set contains the field
        if self.icon_key is None and "icon_key" in self.model_fields_set:
            _dict['iconKey'] = None

        # set to None if icon_source (nullable) is None
        # and model_fields_set contains the field
        if self.icon_source is None and "icon_source" in self.model_fields_set:
            _dict['iconSource'] = None

        # set to None if build_bucket (nullable) is None
        # and model_fields_set contains the field
        if self.build_bucket is None and "build_bucket" in self.model_fields_set:
            _dict['buildBucket'] = None

        # set to None if build_key_id (nullable) is None
        # and model_fields_set contains the field
        if self.build_key_id is None and "build_key_id" in self.model_fields_set:
            _dict['buildKeyId'] = None

        # set to None if pool_domain (nullable) is None
        # and model_fields_set contains the field
        if self.pool_domain is None and "pool_domain" in self.model_fields_set:
            _dict['poolDomain'] = None

        # set to None if pool_label (nullable) is None
        # and model_fields_set contains the field
        if self.pool_label is None and "pool_label" in self.model_fields_set:
            _dict['poolLabel'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deletedAt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        # set to None if access_gate_credential (nullable) is None
        # and model_fields_set contains the field
        if self.access_gate_credential is None and "access_gate_credential" in self.model_fields_set:
            _dict['accessGateCredential'] = None

        # set to None if icon (nullable) is None
        # and model_fields_set contains the field
        if self.icon is None and "icon" in self.model_fields_set:
            _dict['icon'] = None

        # set to None if icon_version (nullable) is None
        # and model_fields_set contains the field
        if self.icon_version is None and "icon_version" in self.model_fields_set:
            _dict['iconVersion'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Application from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organization": obj.get("organization"),
            "slug": obj.get("slug"),
            "name": obj.get("name"),
            "isolationLevel": obj.get("isolationLevel") if obj.get("isolationLevel") is not None else 'shared',
            "serviceAdoption": obj.get("serviceAdoption") if obj.get("serviceAdoption") is not None else 'off',
            "accessGate": obj.get("accessGate") if obj.get("accessGate") is not None else 'none',
            "currentDeployment": obj.get("currentDeployment"),
            "firstRunningAt": obj.get("firstRunningAt"),
            "primaryDeploymentName": obj.get("primaryDeploymentName"),
            "legacyStackBase": obj.get("legacyStackBase"),
            "iconKey": obj.get("iconKey"),
            "iconSource": obj.get("iconSource"),
            "buildBucket": obj.get("buildBucket"),
            "buildKeyId": obj.get("buildKeyId"),
            "deployments": obj.get("deployments"),
            "variables": [Variable.from_dict(_item) for _item in obj["variables"]] if obj.get("variables") is not None else None,
            "portAllocations": [PortAllocation.from_dict(_item) for _item in obj["portAllocations"]] if obj.get("portAllocations") is not None else None,
            "poolDomain": obj.get("poolDomain"),
            "poolLabel": obj.get("poolLabel"),
            "id": obj.get("id"),
            "deletedAt": obj.get("deletedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "buildCredential": SealedSecret.from_dict(obj["buildCredential"]) if obj.get("buildCredential") is not None else None,
            "accessGateCredential": SealedSecret.from_dict(obj["accessGateCredential"]) if obj.get("accessGateCredential") is not None else None,
            "icon": obj.get("icon"),
            "operatorChosenIcon": obj.get("operatorChosenIcon"),
            "iconVersion": obj.get("iconVersion"),
            "deleted": obj.get("deleted")
        })
        return _obj


