# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.deployment_json_merge_patch_build_contexts_value_value import DeploymentJsonMergePatchBuildContextsValueValue
from someones_computer_sdk.models.deployment_json_merge_patch_canonical_spec_value import DeploymentJsonMergePatchCanonicalSpecValue
from someones_computer_sdk.models.deployment_variable import DeploymentVariable
from someones_computer_sdk.models.failure import Failure
from someones_computer_sdk.models.service import Service
from someones_computer_sdk.models.user import User
from typing import Optional, Set
from typing_extensions import Self

class Deployment(BaseModel):
    """
    An IMMUTABLE compose revision. A deploy is a new row; rollback re-points Application::$currentDeployment at an older one. Placement is resolved onto this row (targetSwarm) at deploy time, so migration is just the next revision.
    """ # noqa: E501
    application: Optional[StrictStr] = None
    sequence: Optional[StrictInt] = Field(default=None, description="Monotonic per-application revision number.")
    name: Optional[StrictStr] = Field(default=None, description="What this revision is called — `sc` defaults it to the slugified branch, so the normal shape is a deployment per branch. Null for revisions created before the field existed, or by a client that doesn't send one.")
    raw_compose: Optional[StrictStr] = Field(default=None, description="Exactly what the user submitted.", alias="rawCompose")
    canonical_spec: Optional[Dict[str, DeploymentJsonMergePatchCanonicalSpecValue]] = Field(default=None, description="Parsed, supported-subset-only canonical representation — what {@see \\App\\Service\\Compose\\ComposeParser::parse()} produced. Both keys are optional here and not there: a row is whatever was written when it was written, so a revision that predates a key still has to load.", alias="canonicalSpec")
    build_contexts: Optional[Dict[str, Dict[str, Optional[DeploymentJsonMergePatchBuildContextsValueValue]]]] = Field(default=None, description="Build contexts uploaded with this revision, keyed by compose service name: `{ contextSha256, dockerfile, dockerfileContent?, additionalContexts?, image?, log? }`. The tarballs themselves live in the content-addressed bundle cache ({@see \\App\\Service\\Bundle\\BundleStorage}); this is the pointer the build worker will walk. `dockerfileContent` is a best-effort text preview extracted at ingest ({@see \\App\\Service\\Bundle\\ContextDockerfileReader}) — null when the context was too large to preview or predates this field.", alias="buildContexts")
    forwarded_images: Optional[Dict[str, Dict[str, Optional[StrictStr]]]] = Field(default=None, description="Client-forwarded images uploaded with this revision, keyed by compose service name: `{ contextSha256, originalImage, image?, log? }`. See docs/registry.md's \"Client-side forwarding\" callout: `sc` detects a private, unbuildable `image:` reference it can already reach locally and offers to upload it, for a platform that has no other way to pull it. A sibling to {@see self::$buildContexts} rather than folded into it — that array means \"run this through BuildKit\", and this one never does. The tarballs live in the object store ({@see \\App\\Service\\Bundle\\ImageStorage}), not the database; `image` is filled in once the loader has pushed it to the internal registry, the same way `buildContexts[]['image']` is. `{}` for every revision that forwarded nothing, which is most of them.", alias="forwardedImages")
    build_secrets: Optional[Dict[str, Dict[str, Dict[str, StrictStr]]]] = Field(default=None, description="`build.secrets` values declared for this revision's build services (Grey.ooo/someones.computer_agent#46), sealed the moment they arrive ({@see \\App\\Service\\Secret\\SecretBox}) and never written to the object store the way a build context is: unlike a context tarball, a build secret is live tenant credential material, not something worth caching by content — closer to how {@see \\App\\Service\\Registry\\RegistryTokenSigner} mints a push token than to how {@see \\App\\Entity\\Variable} keeps one.", alias="buildSecrets")
    target_swarm: Optional[StrictStr] = Field(default=None, description="Resolved by the placement engine; null until placed.", alias="targetSwarm")
    status: Optional[StrictStr] = 'pending'
    status_reason: Optional[StrictStr] = Field(default=None, description="Why the revision is in its current status — the build worker's failure message, typically. Null whenever there is nothing to explain.", alias="statusReason")
    failed_on_swarm: Optional[StrictBool] = Field(default=False, description="Set on a `Failed` revision that had already created or updated at least one service on `$targetSwarm` before the failure — a live half-stack, not \"nothing happened\" (#1270). {@see self::isOnASwarm()} reads this for exactly the revisions the ordinary `Deploying`/`Running` check cannot see: whatever partially landed still has to be reachable to a manual Teardown and countable by the stray-container sweep, which is why every other status leaves this false rather than tracking it.", alias="failedOnSwarm")
    zero_task_observed_at: Optional[datetime] = Field(default=None, description="When {@see \\App\\Service\\Reconcile\\RevisionDegradationDetector} first found this `Running` revision with no task actually running on its swarm — null while at least one is, or before it was ever checked.", alias="zeroTaskObservedAt")
    degraded: Optional[StrictBool] = Field(default=False, description="Set once a `Running` revision has gone a full grace period with zero tasks actually running on its swarm (#1279) — a {@see Failure} of {@see \\App\\Enum\\FailurePhase::Runtime} is recorded alongside it. Never flips `$status` itself: `running` still means \"this is what the application should be serving\", and a revision the platform cannot reach a running task for is a fact about the swarm, not a new desired state — the same desired/observed separation {@see \\App\\Service\\Reconcile\\DriftDetector} already keeps at read time, made durable here so it survives past one page view.")
    digest: Optional[StrictStr] = Field(default=None, description="Content digest of the canonical spec, for dedupe/audit.")
    created_by: Optional[User] = Field(default=None, alias="createdBy")
    services: Optional[List[Service]] = None
    variables: Optional[List[DeploymentVariable]] = None
    failures: Optional[List[Failure]] = None
    id: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = Field(default=None, alias="deletedAt")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    on_a_swarm: Optional[StrictBool] = Field(default=None, description="Whether this revision has a stack of its own on a swarm right now.", alias="onASwarm")
    deleted: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["application", "sequence", "name", "rawCompose", "canonicalSpec", "buildContexts", "forwardedImages", "buildSecrets", "targetSwarm", "status", "statusReason", "failedOnSwarm", "zeroTaskObservedAt", "degraded", "digest", "createdBy", "services", "variables", "failures", "id", "deletedAt", "createdAt", "updatedAt", "onASwarm", "deleted"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'building', 'built', 'deploying', 'running', 'failed', 'rolled_back', 'quarantined', 'cancelled']):
            raise ValueError("must be one of enum values ('pending', 'building', 'built', 'deploying', 'running', 'failed', 'rolled_back', 'quarantined', 'cancelled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Deployment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "deleted_at",
            "created_at",
            "updated_at",
            "on_a_swarm",
            "deleted",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in canonical_spec (dict)
        _field_dict = {}
        if self.canonical_spec:
            for _key_canonical_spec in self.canonical_spec:
                if self.canonical_spec[_key_canonical_spec]:
                    _field_dict[_key_canonical_spec] = self.canonical_spec[_key_canonical_spec].to_dict()
            _dict['canonicalSpec'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in build_contexts (dict)
        _field_dict = {}
        if self.build_contexts:
            for _key_build_contexts in self.build_contexts:
                if self.build_contexts[_key_build_contexts]:
                    _field_dict[_key_build_contexts] = self.build_contexts[_key_build_contexts].to_dict()
            _dict['buildContexts'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in services (list)
        _items = []
        if self.services:
            for _item_services in self.services:
                if _item_services:
                    _items.append(_item_services.to_dict())
            _dict['services'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in variables (list)
        _items = []
        if self.variables:
            for _item_variables in self.variables:
                if _item_variables:
                    _items.append(_item_variables.to_dict())
            _dict['variables'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in failures (list)
        _items = []
        if self.failures:
            for _item_failures in self.failures:
                if _item_failures:
                    _items.append(_item_failures.to_dict())
            _dict['failures'] = _items
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if target_swarm (nullable) is None
        # and model_fields_set contains the field
        if self.target_swarm is None and "target_swarm" in self.model_fields_set:
            _dict['targetSwarm'] = None

        # set to None if status_reason (nullable) is None
        # and model_fields_set contains the field
        if self.status_reason is None and "status_reason" in self.model_fields_set:
            _dict['statusReason'] = None

        # set to None if zero_task_observed_at (nullable) is None
        # and model_fields_set contains the field
        if self.zero_task_observed_at is None and "zero_task_observed_at" in self.model_fields_set:
            _dict['zeroTaskObservedAt'] = None

        # set to None if digest (nullable) is None
        # and model_fields_set contains the field
        if self.digest is None and "digest" in self.model_fields_set:
            _dict['digest'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['createdBy'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deletedAt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Deployment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "application": obj.get("application"),
            "sequence": obj.get("sequence"),
            "name": obj.get("name"),
            "rawCompose": obj.get("rawCompose"),
            "canonicalSpec": dict(
                (_k, DeploymentJsonMergePatchCanonicalSpecValue.from_dict(_v))
                for _k, _v in obj["canonicalSpec"].items()
            )
            if obj.get("canonicalSpec") is not None
            else None,
            "buildContexts": dict(
                (_k, dict(
                    (_ik, DeploymentJsonMergePatchBuildContextsValueValue.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj.get("buildContexts").items()
            )
            if obj.get("buildContexts") is not None
            else None,
            "forwardedImages": obj.get("forwardedImages"),
            "buildSecrets": obj.get("buildSecrets"),
            "targetSwarm": obj.get("targetSwarm"),
            "status": obj.get("status") if obj.get("status") is not None else 'pending',
            "statusReason": obj.get("statusReason"),
            "failedOnSwarm": obj.get("failedOnSwarm") if obj.get("failedOnSwarm") is not None else False,
            "zeroTaskObservedAt": obj.get("zeroTaskObservedAt"),
            "degraded": obj.get("degraded") if obj.get("degraded") is not None else False,
            "digest": obj.get("digest"),
            "createdBy": User.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "services": [Service.from_dict(_item) for _item in obj["services"]] if obj.get("services") is not None else None,
            "variables": [DeploymentVariable.from_dict(_item) for _item in obj["variables"]] if obj.get("variables") is not None else None,
            "failures": [Failure.from_dict(_item) for _item in obj["failures"]] if obj.get("failures") is not None else None,
            "id": obj.get("id"),
            "deletedAt": obj.get("deletedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "onASwarm": obj.get("onASwarm"),
            "deleted": obj.get("deleted")
        })
        return _obj


