# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.sealed_secret import SealedSecret
from typing import Optional, Set
from typing_extensions import Self

class DeploymentAccessGate(BaseModel):
    """
    List an application's per-deployment access-gate overrides.
    """ # noqa: E501
    application: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    access_gate: Optional[StrictStr] = Field(default=None, alias="accessGate")
    id: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    access_gate_credential: Optional[SealedSecret] = Field(default=None, alias="accessGateCredential")
    __properties: ClassVar[List[str]] = ["application", "name", "accessGate", "id", "createdAt", "updatedAt", "accessGateCredential"]

    @field_validator('access_gate')
    def access_gate_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'basic_auth', 'token', 'someones_auth']):
            raise ValueError("must be one of enum values ('none', 'basic_auth', 'token', 'someones_auth')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeploymentAccessGate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of access_gate_credential
        if self.access_gate_credential:
            _dict['accessGateCredential'] = self.access_gate_credential.to_dict()
        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        # set to None if access_gate_credential (nullable) is None
        # and model_fields_set contains the field
        if self.access_gate_credential is None and "access_gate_credential" in self.model_fields_set:
            _dict['accessGateCredential'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeploymentAccessGate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "application": obj.get("application"),
            "name": obj.get("name"),
            "accessGate": obj.get("accessGate"),
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "accessGateCredential": SealedSecret.from_dict(obj["accessGateCredential"]) if obj.get("accessGateCredential") is not None else None
        })
        return _obj


