# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from someones_computer_sdk.models.bundle_context_input import BundleContextInput
from someones_computer_sdk.models.bundle_forwarded_image_input import BundleForwardedImageInput
from typing import Optional, Set
from typing_extensions import Self

class DeploymentBundleUploadDeclareInput(BaseModel):
    """
    An IMMUTABLE compose revision. A deploy is a new row; rollback re-points Application::$currentDeployment at an older one. Placement is resolved onto this row (targetSwarm) at deploy time, so migration is just the next revision.
    """ # noqa: E501
    application: Optional[StrictStr]
    client: StrictStr = Field(description="Matches `App\\Service\\Bundle\\BundleManifest::$client` — which client produced this.")
    name: Optional[Annotated[str, Field(strict=True, max_length=63)]] = None
    force: Optional[StrictBool] = Field(default=False, description="Ask for a new revision even if this digest already matches one — {@see BundleManifest::$force}'s own meaning, unchanged.")
    compose: StrictStr
    contexts: Optional[List[BundleContextInput]] = None
    images: Optional[List[BundleForwardedImageInput]] = None
    __properties: ClassVar[List[str]] = ["application", "client", "name", "force", "compose", "contexts", "images"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeploymentBundleUploadDeclareInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in contexts (list)
        _items = []
        if self.contexts:
            for _item_contexts in self.contexts:
                if _item_contexts:
                    _items.append(_item_contexts.to_dict())
            _dict['contexts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in images (list)
        _items = []
        if self.images:
            for _item_images in self.images:
                if _item_images:
                    _items.append(_item_images.to_dict())
            _dict['images'] = _items
        # set to None if application (nullable) is None
        # and model_fields_set contains the field
        if self.application is None and "application" in self.model_fields_set:
            _dict['application'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeploymentBundleUploadDeclareInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "application": obj.get("application"),
            "client": obj.get("client") if obj.get("client") is not None else 'api',
            "name": obj.get("name"),
            "force": obj.get("force") if obj.get("force") is not None else False,
            "compose": obj.get("compose") if obj.get("compose") is not None else '',
            "contexts": [BundleContextInput.from_dict(_item) for _item in obj["contexts"]] if obj.get("contexts") is not None else None,
            "images": [BundleForwardedImageInput.from_dict(_item) for _item in obj["images"]] if obj.get("images") is not None else None
        })
        return _obj


