# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from someones_computer_sdk.models.proxmox_instance import ProxmoxInstance
from someones_computer_sdk.models.user import User
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Failure(BaseModel):
    """
    Failure
    """ # noqa: E501
    deployment: Optional[StrictStr] = Field(default=None, description="Deleting a revision deletes its failures with it. They are an account of what that revision did, and outliving the thing they describe would leave a page that can only render half of itself.", json_schema_extra={"examples": ["https://example.com/"]})
    proxmox_instance: Optional[ProxmoxInstance] = Field(default=None, description="The platform-infrastructure counterpart to {@see $deployment}, set only for a failure that has no revision behind it at all, such as a template build. There's no tenant on the other end of this one: it's reachable only from `/admin`, never from a member's own pages.", alias="proxmoxInstance")
    phase: Optional[StrictStr] = None
    reason: Optional[StrictStr] = Field(default=None, description="Verbatim, as it was written to `Deployment::$statusReason` at the time.")
    reference: Optional[StrictStr] = Field(default=None, description="The short handle this failure is quoted by — see {@see FailureReference}.")
    service: Optional[StrictStr] = Field(default=None, description="Which compose service, where the phase happens per-service. Null for the phases that fail the revision as a whole (placement, stranded) and for a deploy that never got as far as naming one.")
    build_log_key: Optional[StrictStr] = Field(default=None, description="Object key of the build log as it stood, or null when there was none.", alias="buildLogKey")
    image_digest: Optional[StrictStr] = Field(default=None, description="The digest a {@see FailurePhase::Scan} failure was quarantined over — null for every other phase. What lets the scan quarantine queue (docs/image-scanning.md, #816) resolve straight from a quarantined revision to the exact {@see \\App\\Entity\\ImageScan} an operator's Clear or Uphold acts on, without re-deriving it from a pinned image reference or a reason string meant for a person to read.", alias="imageDigest")
    shared_at: Optional[datetime] = Field(default=None, alias="sharedAt")
    share_expires_at: Optional[datetime] = Field(default=None, description="When the capability above stops working, 24 hours after it was minted.", alias="shareExpiresAt")
    shared_by: Optional[User] = Field(default=None, alias="sharedBy")
    id: Optional[UUID] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    display_label: Optional[StrictStr] = Field(default=None, description="The reference as it is written for a reader: `F-24GT1BQ7`.", alias="displayLabel")
    shared: Optional[StrictBool] = Field(default=None, description="Whether an unauthenticated request may read this: a token was minted and it has not yet passed its expiry.")
    __properties: ClassVar[List[str]] = ["deployment", "proxmoxInstance", "phase", "reason", "reference", "service", "buildLogKey", "imageDigest", "sharedAt", "shareExpiresAt", "sharedBy", "id", "createdAt", "updatedAt", "displayLabel", "shared"]

    @field_validator('phase')
    def phase_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['placement', 'build', 'deploy', 'teardown', 'runtime', 'scan', 'stranded', 'infrastructure']):
            raise ValueError("must be one of enum values ('placement', 'build', 'deploy', 'teardown', 'runtime', 'scan', 'stranded', 'infrastructure')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Failure from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "reference",
            "shared_at",
            "share_expires_at",
            "shared_by",
            "id",
            "created_at",
            "updated_at",
            "display_label",
            "shared",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of proxmox_instance
        if self.proxmox_instance:
            _dict['proxmoxInstance'] = self.proxmox_instance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shared_by
        if self.shared_by:
            _dict['sharedBy'] = self.shared_by.to_dict()
        # set to None if deployment (nullable) is None
        # and model_fields_set contains the field
        if self.deployment is None and "deployment" in self.model_fields_set:
            _dict['deployment'] = None

        # set to None if proxmox_instance (nullable) is None
        # and model_fields_set contains the field
        if self.proxmox_instance is None and "proxmox_instance" in self.model_fields_set:
            _dict['proxmoxInstance'] = None

        # set to None if service (nullable) is None
        # and model_fields_set contains the field
        if self.service is None and "service" in self.model_fields_set:
            _dict['service'] = None

        # set to None if build_log_key (nullable) is None
        # and model_fields_set contains the field
        if self.build_log_key is None and "build_log_key" in self.model_fields_set:
            _dict['buildLogKey'] = None

        # set to None if image_digest (nullable) is None
        # and model_fields_set contains the field
        if self.image_digest is None and "image_digest" in self.model_fields_set:
            _dict['imageDigest'] = None

        # set to None if shared_at (nullable) is None
        # and model_fields_set contains the field
        if self.shared_at is None and "shared_at" in self.model_fields_set:
            _dict['sharedAt'] = None

        # set to None if share_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.share_expires_at is None and "share_expires_at" in self.model_fields_set:
            _dict['shareExpiresAt'] = None

        # set to None if shared_by (nullable) is None
        # and model_fields_set contains the field
        if self.shared_by is None and "shared_by" in self.model_fields_set:
            _dict['sharedBy'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Failure from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deployment": obj.get("deployment"),
            "proxmoxInstance": ProxmoxInstance.from_dict(obj["proxmoxInstance"]) if obj.get("proxmoxInstance") is not None else None,
            "phase": obj.get("phase"),
            "reason": obj.get("reason"),
            "reference": obj.get("reference"),
            "service": obj.get("service"),
            "buildLogKey": obj.get("buildLogKey"),
            "imageDigest": obj.get("imageDigest"),
            "sharedAt": obj.get("sharedAt"),
            "shareExpiresAt": obj.get("shareExpiresAt"),
            "sharedBy": User.from_dict(obj["sharedBy"]) if obj.get("sharedBy") is not None else None,
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "displayLabel": obj.get("displayLabel"),
            "shared": obj.get("shared")
        })
        return _obj


