# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.machine import Machine
from someones_computer_sdk.models.membership import Membership
from someones_computer_sdk.models.organization_signal import OrganizationSignal
from someones_computer_sdk.models.user import User
from someones_computer_sdk.models.variable import Variable
from typing import Optional, Set
from typing_extensions import Self

class Organization(BaseModel):
    """
    Ownership and (future) billing boundary. Owns applications, may own BYO swarms.
    """ # noqa: E501
    machine_account: Optional[User] = Field(default=None, alias="machineAccount")
    name: Optional[StrictStr] = None
    slug: Optional[StrictStr] = Field(default=None, description="`unique: true` stops two organizations holding the same *string*; the constraint stops two holding strings that fold to the same **stack name**, which the database has no way to express (#860). Both are needed: the column guards the identifier, the constraint guards what is derived from it.")
    theme: Optional[StrictStr] = Field(default=None, description="The skin this organization's members see, or null to take the instance's.")
    tier_pin: Optional[StrictStr] = Field(default=None, description="An operator's grant of a tier this organization would not reach through any member — {@see \\App\\Enum\\AccountTier::Verified} in particular, which is granted rather than earned and belongs to a contractual relationship with the *organization*, not incidentally to whichever of its members happens to carry the highest personal tier ({@see \\App\\Service\\Trust\\TierResolver::forOrganization()}). A member individually pinned `Verified` still lifts the org the same way a `Trusted` member always has — this pin is for granting it to the org directly, without needing a person to hang it on.", alias="tierPin")
    tier_pinned_at: Optional[datetime] = Field(default=None, alias="tierPinnedAt")
    tier_pinned_by: Optional[User] = Field(default=None, alias="tierPinnedBy")
    tier_pin_reason: Optional[StrictStr] = Field(default=None, alias="tierPinReason")
    low_balance_warned_at: Optional[datetime] = Field(default=None, description="When {@see \\App\\MessageHandler\\CheckRunwayHandler} last warned this organization that its projected runway had dropped below the threshold; null once no warning is outstanding. Set once per crossing and cleared the moment the projection recovers — by a top-up or by the burn easing off — which is what makes \"warn once, re-arm on recovery\" a fact this column can answer rather than something re-derived from the notification table on every tick.", alias="lowBalanceWarnedAt")
    two_factor_required_at: Optional[datetime] = Field(default=None, description="When an Owner/Admin turned on the requirement that every member of this organization protects their account with a second factor; null means it is optional. A reversible policy toggle, stamped like {@see User::$disabledAt} rather than a verdict, so no \"who set it\" attribution.", alias="twoFactorRequiredAt")
    memberships: Optional[List[Membership]] = None
    applications: Optional[List[StrictStr]] = None
    swarms: Optional[List[StrictStr]] = Field(default=None, description="BYO swarms owned by this organization.")
    machines: Optional[List[Machine]] = None
    credit_transactions: Optional[List[StrictStr]] = Field(default=None, description="The append-only credit ledger.", alias="creditTransactions")
    variables: Optional[List[Variable]] = None
    signals: Optional[List[OrganizationSignal]] = None
    id: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = Field(default=None, alias="deletedAt")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    tier_pinned: Optional[StrictBool] = Field(default=None, alias="tierPinned")
    deleted: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["machineAccount", "name", "slug", "theme", "tierPin", "tierPinnedAt", "tierPinnedBy", "tierPinReason", "lowBalanceWarnedAt", "twoFactorRequiredAt", "memberships", "applications", "swarms", "machines", "creditTransactions", "variables", "signals", "id", "deletedAt", "createdAt", "updatedAt", "tierPinned", "deleted"]

    @field_validator('theme')
    def theme_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['house', 'corporate', 'dull', 'plain', 'red-label']):
            raise ValueError("must be one of enum values ('house', 'corporate', 'dull', 'plain', 'red-label')")
        return value

    @field_validator('tier_pin')
    def tier_pin_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['untrusted', 'trusted', 'verified']):
            raise ValueError("must be one of enum values ('untrusted', 'trusted', 'verified')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Organization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "tier_pin",
            "tier_pinned_at",
            "tier_pin_reason",
            "low_balance_warned_at",
            "two_factor_required_at",
            "id",
            "deleted_at",
            "created_at",
            "updated_at",
            "tier_pinned",
            "deleted",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of machine_account
        if self.machine_account:
            _dict['machineAccount'] = self.machine_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tier_pinned_by
        if self.tier_pinned_by:
            _dict['tierPinnedBy'] = self.tier_pinned_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in memberships (list)
        _items = []
        if self.memberships:
            for _item_memberships in self.memberships:
                if _item_memberships:
                    _items.append(_item_memberships.to_dict())
            _dict['memberships'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in machines (list)
        _items = []
        if self.machines:
            for _item_machines in self.machines:
                if _item_machines:
                    _items.append(_item_machines.to_dict())
            _dict['machines'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in variables (list)
        _items = []
        if self.variables:
            for _item_variables in self.variables:
                if _item_variables:
                    _items.append(_item_variables.to_dict())
            _dict['variables'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in signals (list)
        _items = []
        if self.signals:
            for _item_signals in self.signals:
                if _item_signals:
                    _items.append(_item_signals.to_dict())
            _dict['signals'] = _items
        # set to None if machine_account (nullable) is None
        # and model_fields_set contains the field
        if self.machine_account is None and "machine_account" in self.model_fields_set:
            _dict['machineAccount'] = None

        # set to None if theme (nullable) is None
        # and model_fields_set contains the field
        if self.theme is None and "theme" in self.model_fields_set:
            _dict['theme'] = None

        # set to None if tier_pin (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pin is None and "tier_pin" in self.model_fields_set:
            _dict['tierPin'] = None

        # set to None if tier_pinned_at (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pinned_at is None and "tier_pinned_at" in self.model_fields_set:
            _dict['tierPinnedAt'] = None

        # set to None if tier_pinned_by (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pinned_by is None and "tier_pinned_by" in self.model_fields_set:
            _dict['tierPinnedBy'] = None

        # set to None if tier_pin_reason (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pin_reason is None and "tier_pin_reason" in self.model_fields_set:
            _dict['tierPinReason'] = None

        # set to None if low_balance_warned_at (nullable) is None
        # and model_fields_set contains the field
        if self.low_balance_warned_at is None and "low_balance_warned_at" in self.model_fields_set:
            _dict['lowBalanceWarnedAt'] = None

        # set to None if two_factor_required_at (nullable) is None
        # and model_fields_set contains the field
        if self.two_factor_required_at is None and "two_factor_required_at" in self.model_fields_set:
            _dict['twoFactorRequiredAt'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deletedAt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Organization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "machineAccount": User.from_dict(obj["machineAccount"]) if obj.get("machineAccount") is not None else None,
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "theme": obj.get("theme"),
            "tierPin": obj.get("tierPin"),
            "tierPinnedAt": obj.get("tierPinnedAt"),
            "tierPinnedBy": User.from_dict(obj["tierPinnedBy"]) if obj.get("tierPinnedBy") is not None else None,
            "tierPinReason": obj.get("tierPinReason"),
            "lowBalanceWarnedAt": obj.get("lowBalanceWarnedAt"),
            "twoFactorRequiredAt": obj.get("twoFactorRequiredAt"),
            "memberships": [Membership.from_dict(_item) for _item in obj["memberships"]] if obj.get("memberships") is not None else None,
            "applications": obj.get("applications"),
            "swarms": obj.get("swarms"),
            "machines": [Machine.from_dict(_item) for _item in obj["machines"]] if obj.get("machines") is not None else None,
            "creditTransactions": obj.get("creditTransactions"),
            "variables": [Variable.from_dict(_item) for _item in obj["variables"]] if obj.get("variables") is not None else None,
            "signals": [OrganizationSignal.from_dict(_item) for _item in obj["signals"]] if obj.get("signals") is not None else None,
            "id": obj.get("id"),
            "deletedAt": obj.get("deletedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "tierPinned": obj.get("tierPinned"),
            "deleted": obj.get("deleted")
        })
        return _obj


