# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProxmoxInstance(BaseModel):
    """
    ProxmoxInstance
    """ # noqa: E501
    name: Optional[StrictStr] = None
    endpoint: Optional[StrictStr] = Field(default=None, description="Base URL of the API, scheme and authority only — `https://10.0.0.68:8006`.")
    token_id: Optional[StrictStr] = Field(default=None, description="Full token identifier, `user@realm!tokenid` — e.g. `root@pam!someones-computer`.", alias="tokenId")
    token_secret: Optional[StrictStr] = Field(default=None, description="The token's secret (a UUID as Proxmox issues it), encrypted at rest and never serialized. Proxmox shows it exactly once, at creation.", alias="tokenSecret")
    verify_tls: Optional[StrictBool] = Field(default=True, description="Whether the certificate must validate against a CA chain.", alias="verifyTls")
    public_key_pin: Optional[StrictStr] = Field(default=None, description="base64 SHA-256 of the endpoint's SubjectPublicKeyInfo — curl's `pin-sha256`. The right answer for a self-signed Proxmox: it authenticates *this specific host* without any CA, so the connection is still protected against interception, which `verifyTls = false` alone is not.", alias="publicKeyPin")
    status: Optional[StrictStr] = 'unreachable'
    last_seen_at: Optional[datetime] = Field(default=None, alias="lastSeenAt")
    last_error: Optional[StrictStr] = Field(default=None, description="Why the last probe failed, kept so an operator can tell a revoked token from a dead host without re-running anything. Cleared on success.", alias="lastError")
    version: Optional[Dict[str, Optional[StrictStr]]] = Field(default=None, description="Observed `GET /version` snapshot (release, repoid). Observed state, so it is whatever the last probe saw and is never authoritative.")
    template_vmid: Optional[StrictInt] = Field(default=None, description="The vmid of the Alpine template `app:proxmox:template` last built here, or null if it has never been run against this endpoint. This is what makes a template's existence something the app can answer without an SSH session and a `qm list` — the gap that sent an operator to do exactly that.", alias="templateVmid")
    template_alpine_version: Optional[StrictStr] = Field(default=None, description="The Alpine version baked into {@see $templateVmid}, e.g. `3.23.0`.", alias="templateAlpineVersion")
    template_built_at: Optional[datetime] = Field(default=None, alias="templateBuiltAt")
    template_build_started_at: Optional[datetime] = Field(default=None, description="When a background template build was dispatched for this endpoint, or null when none is in flight — the only trace a build leaves while it runs.", alias="templateBuildStartedAt")
    template_build_failures: Optional[StrictInt] = Field(default=0, description="How many builds in a row have failed since the last success, incremented by {@see \\App\\MessageHandler\\BuildProxmoxTemplateHandler}'s catch block and cleared by {@see recordTemplateBuilt()}. This is what {@see templateBuildIsBackedOff()} backs the retry off against — without it, {@see \\App\\MessageHandler\\CheckProxmoxTemplatesHandler} redispatches a build every tick regardless of how many times it has already failed (#1059).", alias="templateBuildFailures")
    id: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    template: Optional[StrictBool] = Field(default=None, description="Whether `app:proxmox:template` has ever recorded a build against this endpoint.")
    __properties: ClassVar[List[str]] = ["name", "endpoint", "tokenId", "tokenSecret", "verifyTls", "publicKeyPin", "status", "lastSeenAt", "lastError", "version", "templateVmid", "templateAlpineVersion", "templateBuiltAt", "templateBuildStartedAt", "templateBuildFailures", "id", "createdAt", "updatedAt", "template"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reachable', 'unreachable', 'unauthorized']):
            raise ValueError("must be one of enum values ('reachable', 'unreachable', 'unauthorized')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProxmoxInstance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "template_vmid",
            "template_alpine_version",
            "template_built_at",
            "template_build_started_at",
            "template_build_failures",
            "id",
            "created_at",
            "updated_at",
            "template",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if public_key_pin (nullable) is None
        # and model_fields_set contains the field
        if self.public_key_pin is None and "public_key_pin" in self.model_fields_set:
            _dict['publicKeyPin'] = None

        # set to None if last_seen_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_seen_at is None and "last_seen_at" in self.model_fields_set:
            _dict['lastSeenAt'] = None

        # set to None if last_error (nullable) is None
        # and model_fields_set contains the field
        if self.last_error is None and "last_error" in self.model_fields_set:
            _dict['lastError'] = None

        # set to None if template_vmid (nullable) is None
        # and model_fields_set contains the field
        if self.template_vmid is None and "template_vmid" in self.model_fields_set:
            _dict['templateVmid'] = None

        # set to None if template_alpine_version (nullable) is None
        # and model_fields_set contains the field
        if self.template_alpine_version is None and "template_alpine_version" in self.model_fields_set:
            _dict['templateAlpineVersion'] = None

        # set to None if template_built_at (nullable) is None
        # and model_fields_set contains the field
        if self.template_built_at is None and "template_built_at" in self.model_fields_set:
            _dict['templateBuiltAt'] = None

        # set to None if template_build_started_at (nullable) is None
        # and model_fields_set contains the field
        if self.template_build_started_at is None and "template_build_started_at" in self.model_fields_set:
            _dict['templateBuildStartedAt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProxmoxInstance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "endpoint": obj.get("endpoint"),
            "tokenId": obj.get("tokenId"),
            "tokenSecret": obj.get("tokenSecret"),
            "verifyTls": obj.get("verifyTls") if obj.get("verifyTls") is not None else True,
            "publicKeyPin": obj.get("publicKeyPin"),
            "status": obj.get("status") if obj.get("status") is not None else 'unreachable',
            "lastSeenAt": obj.get("lastSeenAt"),
            "lastError": obj.get("lastError"),
            "version": obj.get("version"),
            "templateVmid": obj.get("templateVmid"),
            "templateAlpineVersion": obj.get("templateAlpineVersion"),
            "templateBuiltAt": obj.get("templateBuiltAt"),
            "templateBuildStartedAt": obj.get("templateBuildStartedAt"),
            "templateBuildFailures": obj.get("templateBuildFailures") if obj.get("templateBuildFailures") is not None else 0,
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "template": obj.get("template")
        })
        return _obj


