# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.service_cpu_limit import ServiceCpuLimit
from someones_computer_sdk.models.service_cpu_reservation import ServiceCpuReservation
from someones_computer_sdk.models.service_healthcheck_value import ServiceHealthcheckValue
from someones_computer_sdk.models.service_mem_limit import ServiceMemLimit
from someones_computer_sdk.models.service_mem_reservation import ServiceMemReservation
from someones_computer_sdk.models.service_ports_inner_value import ServicePortsInnerValue
from typing import Optional, Set
from typing_extensions import Self

class Service(BaseModel):
    """
    Service
    """ # noqa: E501
    deployment: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    image: Optional[StrictStr] = None
    replicas: Optional[StrictInt] = 1
    cpu_limit: Optional[ServiceCpuLimit] = Field(default=None, alias="cpuLimit")
    mem_limit: Optional[ServiceMemLimit] = Field(default=None, alias="memLimit")
    cpu_reservation: Optional[ServiceCpuReservation] = Field(default=None, alias="cpuReservation")
    mem_reservation: Optional[ServiceMemReservation] = Field(default=None, alias="memReservation")
    ports: Optional[List[Dict[str, ServicePortsInnerValue]]] = None
    http_port: Optional[StrictInt] = Field(default=None, description="The container port this service speaks HTTP on, as compose's `x-someones.http` declared it — null means nothing was declared and {@see \\App\\Service\\Ingress\\IngressPlanner} falls back to the well-known ports.", alias="httpPort")
    command: Optional[List[StrictStr]] = Field(default=None, description="The container's argv, as compose `command:` declared it — already split into words by the parser, because Swarm's `Args` is argv rather than a line.")
    entrypoint: Optional[List[StrictStr]] = Field(default=None, description="The container's `Command` — compose `entrypoint:`, which replaces the image's own `ENTRYPOINT` rather than feeding it, unlike {@see $command}.")
    healthcheck: Optional[Dict[str, Optional[ServiceHealthcheckValue]]] = Field(default=None, description="Compose `healthcheck:`, projected straight from {@see \\App\\Service\\Compose\\ComposeParser::healthcheck()} into the shape {@see \\App\\Service\\Deploy\\StackDeployer} sends as Swarm's `ContainerSpec.Healthcheck` — `test` is a `NONE`/`CMD`/`CMD-SHELL` argv, the rest are nanoseconds/a count. Null means nothing was declared, so an image's own baked-in `HEALTHCHECK` (or none) stands; `disable: true` in the compose file is not null, it is `test: [\"NONE\"]` — an explicit instruction rather than silence.")
    restart: Optional[StrictStr] = Field(default='always', description="What happens when a container exits; also decides service vs job.")
    forwarded_unscanned: Optional[StrictBool] = Field(default=False, description="Set while this service's image arrived by client-side forwarding (docs/registry.md's \"Client-side forwarding\" callout) and no scan verdict is yet on record for the digest it was pinned to — bytes from a user's machine, not a source tree we built or a registry we chose to trust. A forwarded image is scanned as it loads ({@see \\App\\MessageHandler\\BuildBundleHandler}), so this is normally cleared by the time the service is projected; one left set is a forwarded image that reached deploy unvetted, which {@see \\App\\MessageHandler\\DeployRevisionHandler} refuses to run (docs/image-scanning.md).", alias="forwardedUnscanned")
    id: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["deployment", "name", "image", "replicas", "cpuLimit", "memLimit", "cpuReservation", "memReservation", "ports", "httpPort", "command", "entrypoint", "healthcheck", "restart", "forwardedUnscanned", "id", "createdAt", "updatedAt"]

    @field_validator('restart')
    def restart_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['always', 'on-failure', 'never']):
            raise ValueError("must be one of enum values ('always', 'on-failure', 'never')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Service from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cpu_limit
        if self.cpu_limit:
            _dict['cpuLimit'] = self.cpu_limit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mem_limit
        if self.mem_limit:
            _dict['memLimit'] = self.mem_limit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cpu_reservation
        if self.cpu_reservation:
            _dict['cpuReservation'] = self.cpu_reservation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mem_reservation
        if self.mem_reservation:
            _dict['memReservation'] = self.mem_reservation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ports (list)
        _items = []
        if self.ports:
            for _item_ports in self.ports:
                if _item_ports:
                    _items.append(_item_ports.to_dict())
            _dict['ports'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in healthcheck (dict)
        _field_dict = {}
        if self.healthcheck:
            for _key_healthcheck in self.healthcheck:
                if self.healthcheck[_key_healthcheck]:
                    _field_dict[_key_healthcheck] = self.healthcheck[_key_healthcheck].to_dict()
            _dict['healthcheck'] = _field_dict
        # set to None if cpu_limit (nullable) is None
        # and model_fields_set contains the field
        if self.cpu_limit is None and "cpu_limit" in self.model_fields_set:
            _dict['cpuLimit'] = None

        # set to None if mem_limit (nullable) is None
        # and model_fields_set contains the field
        if self.mem_limit is None and "mem_limit" in self.model_fields_set:
            _dict['memLimit'] = None

        # set to None if cpu_reservation (nullable) is None
        # and model_fields_set contains the field
        if self.cpu_reservation is None and "cpu_reservation" in self.model_fields_set:
            _dict['cpuReservation'] = None

        # set to None if mem_reservation (nullable) is None
        # and model_fields_set contains the field
        if self.mem_reservation is None and "mem_reservation" in self.model_fields_set:
            _dict['memReservation'] = None

        # set to None if ports (nullable) is None
        # and model_fields_set contains the field
        if self.ports is None and "ports" in self.model_fields_set:
            _dict['ports'] = None

        # set to None if http_port (nullable) is None
        # and model_fields_set contains the field
        if self.http_port is None and "http_port" in self.model_fields_set:
            _dict['httpPort'] = None

        # set to None if command (nullable) is None
        # and model_fields_set contains the field
        if self.command is None and "command" in self.model_fields_set:
            _dict['command'] = None

        # set to None if entrypoint (nullable) is None
        # and model_fields_set contains the field
        if self.entrypoint is None and "entrypoint" in self.model_fields_set:
            _dict['entrypoint'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Service from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deployment": obj.get("deployment"),
            "name": obj.get("name"),
            "image": obj.get("image"),
            "replicas": obj.get("replicas") if obj.get("replicas") is not None else 1,
            "cpuLimit": ServiceCpuLimit.from_dict(obj["cpuLimit"]) if obj.get("cpuLimit") is not None else None,
            "memLimit": ServiceMemLimit.from_dict(obj["memLimit"]) if obj.get("memLimit") is not None else None,
            "cpuReservation": ServiceCpuReservation.from_dict(obj["cpuReservation"]) if obj.get("cpuReservation") is not None else None,
            "memReservation": ServiceMemReservation.from_dict(obj["memReservation"]) if obj.get("memReservation") is not None else None,
            "ports": [Dict[str, ServicePortsInnerValue].from_dict(_item) for _item in obj["ports"]] if obj.get("ports") is not None else None,
            "httpPort": obj.get("httpPort"),
            "command": obj.get("command"),
            "entrypoint": obj.get("entrypoint"),
            "healthcheck": dict(
                (_k, ServiceHealthcheckValue.from_dict(_v))
                for _k, _v in obj["healthcheck"].items()
            )
            if obj.get("healthcheck") is not None
            else None,
            "restart": obj.get("restart") if obj.get("restart") is not None else 'always',
            "forwardedUnscanned": obj.get("forwardedUnscanned") if obj.get("forwardedUnscanned") is not None else False,
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


