# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.sealed_secret import SealedSecret
from typing import Optional, Set
from typing_extensions import Self

class ServiceBinding(BaseModel):
    """
    That an application may use a managed service — the join the per-application toggle could not express.  Many-to-many by construction: one database can back a web app and its worker, and one application can hold several bindings. Unbinding leaves the data alone; only destroying the {@see ManagedService} touches it.  A binding is also where the *deployment* seam lives. It records which variable names it injects, so the UI can say what an application will receive before it receives it, and so the resolver can show an operator-set variable shadowing a binding rather than silently losing to it.  **Creating one is a permission, not a provisioning step** — nothing at the engine moves. Deleting one withdraws that permission and touches no data, which is why `DELETE` here is a hard delete and `DELETE` on a {@see ManagedService} is not the same kind of verb at all.
    """ # noqa: E501
    application: Optional[StrictStr] = None
    service: Optional[StrictStr] = None
    injected_keys: Optional[List[StrictStr]] = Field(default=None, description="The environment variable names this binding contributes — one `DATABASE_URL` for a database, the four `S3_*` names for a bucket.", alias="injectedKeys")
    sidecar_service_name: Optional[StrictStr] = Field(default='db', description="What the sidecar is called inside the tenant's stack — `db` unless something else claimed the name first.", alias="sidecarServiceName")
    adopted_compose_service: Optional[StrictStr] = Field(default=None, description="The compose service this binding replaced, or null for a binding somebody asked for directly.", alias="adoptedComposeService")
    id: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    adopted: Optional[StrictBool] = None
    sidecar_credential: Optional[SealedSecret] = Field(default=None, alias="sidecarCredential")
    __properties: ClassVar[List[str]] = ["application", "service", "injectedKeys", "sidecarServiceName", "adoptedComposeService", "id", "createdAt", "updatedAt", "adopted", "sidecarCredential"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceBinding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "updated_at",
            "adopted",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sidecar_credential
        if self.sidecar_credential:
            _dict['sidecarCredential'] = self.sidecar_credential.to_dict()
        # set to None if adopted_compose_service (nullable) is None
        # and model_fields_set contains the field
        if self.adopted_compose_service is None and "adopted_compose_service" in self.model_fields_set:
            _dict['adoptedComposeService'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceBinding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "application": obj.get("application"),
            "service": obj.get("service"),
            "injectedKeys": obj.get("injectedKeys"),
            "sidecarServiceName": obj.get("sidecarServiceName") if obj.get("sidecarServiceName") is not None else 'db',
            "adoptedComposeService": obj.get("adoptedComposeService"),
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "adopted": obj.get("adopted"),
            "sidecarCredential": SealedSecret.from_dict(obj["sidecarCredential"]) if obj.get("sidecarCredential") is not None else None
        })
        return _obj


