# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.machine import Machine
from someones_computer_sdk.models.swarm_node import SwarmNode
from typing import Optional, Set
from typing_extensions import Self

class Swarm(BaseModel):
    """
    A Docker Swarm we can deploy onto. The trust boundary of the platform.  owner === null  => PLATFORM pool (shared infra we run). owner !== null  => CUSTOMER BYO cluster (untrusted, outbound-only).
    """ # noqa: E501
    owner: Optional[StrictStr] = Field(default=None, description="Null for the platform pool; set for a customer BYO cluster.")
    kind: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    endpoint: Optional[StrictStr] = Field(default=None, description="Manager API endpoint (tcp+TLS) or SSH target.")
    status: Optional[StrictStr] = 'unreachable'
    public_host: Optional[StrictStr] = Field(default=None, description="The address a client *outside* the cluster reaches this context's published ports on — a hostname or an IP, no scheme and no port.", alias="publicHost")
    roles: Optional[List[StrictStr]] = Field(default=None, description="What this context is used for — builds, runtime, or both. Stored as the enum's string values rather than a relation: it is a small fixed set, and a json column needs no join to answer \"where can I build?\".")
    last_seen_at: Optional[datetime] = Field(default=None, alias="lastSeenAt")
    capacity: Optional[Dict[str, Optional[StrictStr]]] = Field(default=None, description="Observed capacity snapshot (cpu/mem/nodes), reconciled from the swarm — whatever {@see \\App\\Service\\Swarm\\SwarmHealth::$capacity} carried at the last successful probe.")
    labels: Optional[Dict[str, StrictStr]] = None
    ingress_installed_at: Optional[datetime] = Field(default=None, description="When {@see \\App\\Service\\Ingress\\TraefikInstaller} last stood up (or confirmed) the edge on this context, dispatched automatically once it becomes a platform-owned runtime context.", alias="ingressInstalledAt")
    ingress_error: Optional[StrictStr] = Field(default=None, description="What the last automatic install attempt said, when it failed. Cleared on a success so the row never shows a stale complaint next to a working edge.", alias="ingressError")
    ingress_network: Optional[StrictStr] = Field(default=None, description="The shared overlay that install put the edge on — the one Traefik's `--providers.swarm.network` names, and therefore the only network a service can be routed from.", alias="ingressNetwork")
    ingress_verified_at: Optional[datetime] = Field(default=None, description="When the edge was last *observed* routing — the overlay present, the edge service on it, watching it, with a task running ({@see \\App\\Service\\Ingress\\IngressVerifier}).", alias="ingressVerifiedAt")
    ingress_verification_error: Optional[StrictStr] = Field(default=None, description="What the last verification found wrong, or null when the edge was routing.", alias="ingressVerificationError")
    nodes: Optional[List[SwarmNode]] = None
    machines: Optional[List[Machine]] = None
    deployments: Optional[List[StrictStr]] = Field(default=None, description="The revisions placed here. Mapped for the same single reason as {@see self::$machines} — so a delete can let go of them — rather than as a collection anything reads; {@see \\App\\Repository\\DeploymentRepository} is where a caller asks what is on a context.")
    id: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = Field(default=None, alias="deletedAt")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    platform_owned: Optional[StrictBool] = Field(default=None, alias="platformOwned")
    platform_provisioned: Optional[StrictBool] = Field(default=None, description="Whether the platform itself stood this context up, whoever currently owns the row — a machine {@see \\App\\MessageHandler\\ProvisionMachineHandler} provisioned, running this platform's own trusted image, versus a customer's own cluster registered straight through {@see \\App\\Controller\\Admin\\SwarmController}.", alias="platformProvisioned")
    working_edge: Optional[StrictBool] = Field(default=None, description="Whether a revision that publishes a port can be routed here.", alias="workingEdge")
    deleted: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["owner", "kind", "name", "endpoint", "status", "publicHost", "roles", "lastSeenAt", "capacity", "labels", "ingressInstalledAt", "ingressError", "ingressNetwork", "ingressVerifiedAt", "ingressVerificationError", "nodes", "machines", "deployments", "id", "deletedAt", "createdAt", "updatedAt", "platformOwned", "platformProvisioned", "workingEdge", "deleted"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['platform', 'customer']):
            raise ValueError("must be one of enum values ('platform', 'customer')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reachable', 'unreachable', 'draining']):
            raise ValueError("must be one of enum values ('reachable', 'unreachable', 'draining')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Swarm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "kind",
            "labels",
            "ingress_installed_at",
            "ingress_error",
            "ingress_network",
            "ingress_verified_at",
            "ingress_verification_error",
            "id",
            "deleted_at",
            "created_at",
            "updated_at",
            "platform_owned",
            "platform_provisioned",
            "working_edge",
            "deleted",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                if _item_nodes:
                    _items.append(_item_nodes.to_dict())
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in machines (list)
        _items = []
        if self.machines:
            for _item_machines in self.machines:
                if _item_machines:
                    _items.append(_item_machines.to_dict())
            _dict['machines'] = _items
        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        # set to None if public_host (nullable) is None
        # and model_fields_set contains the field
        if self.public_host is None and "public_host" in self.model_fields_set:
            _dict['publicHost'] = None

        # set to None if last_seen_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_seen_at is None and "last_seen_at" in self.model_fields_set:
            _dict['lastSeenAt'] = None

        # set to None if ingress_installed_at (nullable) is None
        # and model_fields_set contains the field
        if self.ingress_installed_at is None and "ingress_installed_at" in self.model_fields_set:
            _dict['ingressInstalledAt'] = None

        # set to None if ingress_error (nullable) is None
        # and model_fields_set contains the field
        if self.ingress_error is None and "ingress_error" in self.model_fields_set:
            _dict['ingressError'] = None

        # set to None if ingress_network (nullable) is None
        # and model_fields_set contains the field
        if self.ingress_network is None and "ingress_network" in self.model_fields_set:
            _dict['ingressNetwork'] = None

        # set to None if ingress_verified_at (nullable) is None
        # and model_fields_set contains the field
        if self.ingress_verified_at is None and "ingress_verified_at" in self.model_fields_set:
            _dict['ingressVerifiedAt'] = None

        # set to None if ingress_verification_error (nullable) is None
        # and model_fields_set contains the field
        if self.ingress_verification_error is None and "ingress_verification_error" in self.model_fields_set:
            _dict['ingressVerificationError'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deletedAt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Swarm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "owner": obj.get("owner"),
            "kind": obj.get("kind"),
            "name": obj.get("name"),
            "endpoint": obj.get("endpoint"),
            "status": obj.get("status") if obj.get("status") is not None else 'unreachable',
            "publicHost": obj.get("publicHost"),
            "roles": obj.get("roles"),
            "lastSeenAt": obj.get("lastSeenAt"),
            "capacity": obj.get("capacity"),
            "labels": obj.get("labels"),
            "ingressInstalledAt": obj.get("ingressInstalledAt"),
            "ingressError": obj.get("ingressError"),
            "ingressNetwork": obj.get("ingressNetwork"),
            "ingressVerifiedAt": obj.get("ingressVerifiedAt"),
            "ingressVerificationError": obj.get("ingressVerificationError"),
            "nodes": [SwarmNode.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "machines": [Machine.from_dict(_item) for _item in obj["machines"]] if obj.get("machines") is not None else None,
            "deployments": obj.get("deployments"),
            "id": obj.get("id"),
            "deletedAt": obj.get("deletedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "platformOwned": obj.get("platformOwned"),
            "platformProvisioned": obj.get("platformProvisioned"),
            "workingEdge": obj.get("workingEdge"),
            "deleted": obj.get("deleted")
        })
        return _obj


