# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.user_avatar_photo import UserAvatarPhoto
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    User
    """ # noqa: E501
    email: Optional[StrictStr] = None
    username: Optional[StrictStr] = Field(default=None, description="Handle the user can sign in with instead of their email.")
    display_name: Optional[StrictStr] = Field(default=None, alias="displayName")
    theme: Optional[StrictStr] = Field(default=None, description="Which skin this person prefers, or null to take whatever their organization or the instance says.")
    locale: Optional[StrictStr] = Field(default=None, description="Which locale this person prefers, or null for no explicit choice — the same shape as {@see self::$theme}: null is not `en_GB`, it is \"let the cascade decide\" (cookie, then `Accept-Language`, then the instance default). See {@see \\App\\Service\\LocaleResolver} and docs/internationalization.md.")
    timezone: Optional[StrictStr] = Field(default=None, description="The IANA timezone identifier (e.g. `Europe/London`) this person prefers, or null for no explicit choice — the same shape as {@see self::$locale}: null is not UTC, it is \"let the cascade decide\" (cookie written by the browser's own auto-detection, then the instance default). A plain validated string rather than a backed enum like {@see self::$theme}/{@see self::$locale}: the IANA database has ~400 identifiers, too many for an enum to curate the way {@see \\App\\Enum\\Locale} deliberately does for its two cases. See {@see \\App\\Service\\TimezoneResolver}.")
    password: Optional[StrictStr] = Field(default=None, description="Hashed password; null for accounts that authenticate only via OAuth or LDAP.")
    ldap_dn: Optional[StrictStr] = Field(default=None, description="The bound entry's distinguished name in LLDAP. Presence means the account is LDAP-authoritative: {@see App\\Service\\LdapAccountLinker} clears any local password when it sets this, and it is never set alongside one.", alias="ldapDn")
    avatar_photo: Optional[UserAvatarPhoto] = Field(default=None, alias="avatarPhoto")
    roles: Optional[List[StrictStr]] = None
    disabled_at: Optional[datetime] = Field(default=None, description="Set when a platform operator suspends the account; null = active.", alias="disabledAt")
    spam_marked_at: Optional[datetime] = Field(default=None, description="When an operator judged this account to be spam; null = not spam.", alias="spamMarkedAt")
    spam_marked_by: Optional[User] = Field(default=None, alias="spamMarkedBy")
    approved_at: Optional[datetime] = Field(default=None, description="When an operator approved the account; null means it is still waiting and can reach nothing but the holding page ({@see self::getRoles()}).", alias="approvedAt")
    email_confirmed_at: Optional[datetime] = Field(default=None, description="When the address on this account was proven to be one the person can read; null means it never was ({@see \\App\\Service\\EmailConfirmationService}).", alias="emailConfirmedAt")
    credit_granted_at: Optional[datetime] = Field(default=None, description="When the one-off signup credit was granted ({@see \\App\\Service\\Credit\\SignupGrant}).", alias="creditGrantedAt")
    tier_pin: Optional[StrictStr] = Field(default=None, description="An operator's override of the trust tier this account would otherwise progress into on its own; null means the automatic rule decides ({@see \\App\\Service\\Trust\\TierResolver}).", alias="tierPin")
    tier_pinned_at: Optional[datetime] = Field(default=None, alias="tierPinnedAt")
    tier_pinned_by: Optional[User] = Field(default=None, alias="tierPinnedBy")
    tier_pin_reason: Optional[StrictStr] = Field(default=None, alias="tierPinReason")
    oauth_identities: Optional[List[OAuthIdentity]] = Field(default=None, alias="oauthIdentities")
    totp_secret: Optional[StrictStr] = Field(default=None, description="The TOTP shared secret, **encrypted at rest** ({@see \\App\\Service\\TwoFactor\\TotpSecretCipher}), or null for an account that has not enabled a second factor.", alias="totpSecret")
    totp_secret_key_id: Optional[StrictStr] = Field(default=None, description="Which key wrapped {@see self::$totpSecret}, so a key rotation can re-wrap it without users re-enrolling ({@see \\App\\Service\\TwoFactor\\TotpSecretCipher}).", alias="totpSecretKeyId")
    totp_confirmed_at: Optional[datetime] = Field(default=None, description="When the person proved the authenticator by entering a live code; null means 2FA is not in force for this account. This is the flag the step-up gate reads ({@see \\App\\EventSubscriber\\TwoFactorStepUpSubscriber}).", alias="totpConfirmedAt")
    recovery_codes: Optional[List[RecoveryCode]] = Field(default=None, alias="recoveryCodes")
    machine_for: Optional[StrictStr] = Field(default=None, description="The organization this account exists to act for, or null for a person.", alias="machineFor")
    id: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = Field(default=None, alias="deletedAt")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    display_label: Optional[StrictStr] = Field(default=None, description="How this person is named in the UI. Registration requires a display name, but an OAuth provider may not share one, so the handle stands in — never the email address, which is not ours to show.", alias="displayLabel")
    machine: Optional[StrictBool] = Field(default=None, description="Whether this account is a machine acting for an organization, not a person.")
    ldap_managed: Optional[StrictBool] = Field(default=None, alias="ldapManaged")
    avatar_photo_type: Optional[StrictStr] = Field(default=None, alias="avatarPhotoType")
    user_identifier: Optional[StrictStr] = Field(default=None, description="The identifier stored in the session token. Sign-in accepts either the email or the username ({@see UserRepository::loadUserByIdentifier()}); this is the canonical one the token is refreshed from.", alias="userIdentifier")
    granted_roles: Optional[List[StrictStr]] = Field(default=None, description="The roles the account actually carries, whether or not it has been approved — what the admin panel shows and what the feature toggles flip.", alias="grantedRoles")
    disabled: Optional[StrictBool] = None
    spam: Optional[StrictBool] = None
    approved: Optional[StrictBool] = None
    email_confirmed: Optional[StrictBool] = Field(default=None, alias="emailConfirmed")
    tier_pinned: Optional[StrictBool] = Field(default=None, alias="tierPinned")
    totp_enabled: Optional[StrictBool] = Field(default=None, description="True once the person has proved the authenticator — the gate's on/off switch.", alias="totpEnabled")
    deleted: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["email", "username", "displayName", "theme", "locale", "timezone", "password", "ldapDn", "avatarPhoto", "roles", "disabledAt", "spamMarkedAt", "spamMarkedBy", "approvedAt", "emailConfirmedAt", "creditGrantedAt", "tierPin", "tierPinnedAt", "tierPinnedBy", "tierPinReason", "oauthIdentities", "totpSecret", "totpSecretKeyId", "totpConfirmedAt", "recoveryCodes", "machineFor", "id", "deletedAt", "createdAt", "updatedAt", "displayLabel", "machine", "ldapManaged", "avatarPhotoType", "userIdentifier", "grantedRoles", "disabled", "spam", "approved", "emailConfirmed", "tierPinned", "totpEnabled", "deleted"]

    @field_validator('theme')
    def theme_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['house', 'corporate', 'dull', 'plain', 'red-label']):
            raise ValueError("must be one of enum values ('house', 'corporate', 'dull', 'plain', 'red-label')")
        return value

    @field_validator('locale')
    def locale_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['en_GB', 'en_US']):
            raise ValueError("must be one of enum values ('en_GB', 'en_US')")
        return value

    @field_validator('tier_pin')
    def tier_pin_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['untrusted', 'trusted', 'verified']):
            raise ValueError("must be one of enum values ('untrusted', 'trusted', 'verified')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "disabled_at",
            "spam_marked_at",
            "approved_at",
            "email_confirmed_at",
            "credit_granted_at",
            "tier_pin",
            "tier_pinned_at",
            "tier_pin_reason",
            "totp_secret_key_id",
            "totp_confirmed_at",
            "id",
            "deleted_at",
            "created_at",
            "updated_at",
            "display_label",
            "machine",
            "ldap_managed",
            "avatar_photo_type",
            "user_identifier",
            "disabled",
            "spam",
            "approved",
            "email_confirmed",
            "tier_pinned",
            "totp_enabled",
            "deleted",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of avatar_photo
        if self.avatar_photo:
            _dict['avatarPhoto'] = self.avatar_photo.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spam_marked_by
        if self.spam_marked_by:
            _dict['spamMarkedBy'] = self.spam_marked_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tier_pinned_by
        if self.tier_pinned_by:
            _dict['tierPinnedBy'] = self.tier_pinned_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in oauth_identities (list)
        _items = []
        if self.oauth_identities:
            for _item_oauth_identities in self.oauth_identities:
                if _item_oauth_identities:
                    _items.append(_item_oauth_identities.to_dict())
            _dict['oauthIdentities'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recovery_codes (list)
        _items = []
        if self.recovery_codes:
            for _item_recovery_codes in self.recovery_codes:
                if _item_recovery_codes:
                    _items.append(_item_recovery_codes.to_dict())
            _dict['recoveryCodes'] = _items
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['displayName'] = None

        # set to None if theme (nullable) is None
        # and model_fields_set contains the field
        if self.theme is None and "theme" in self.model_fields_set:
            _dict['theme'] = None

        # set to None if locale (nullable) is None
        # and model_fields_set contains the field
        if self.locale is None and "locale" in self.model_fields_set:
            _dict['locale'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if ldap_dn (nullable) is None
        # and model_fields_set contains the field
        if self.ldap_dn is None and "ldap_dn" in self.model_fields_set:
            _dict['ldapDn'] = None

        # set to None if avatar_photo (nullable) is None
        # and model_fields_set contains the field
        if self.avatar_photo is None and "avatar_photo" in self.model_fields_set:
            _dict['avatarPhoto'] = None

        # set to None if disabled_at (nullable) is None
        # and model_fields_set contains the field
        if self.disabled_at is None and "disabled_at" in self.model_fields_set:
            _dict['disabledAt'] = None

        # set to None if spam_marked_at (nullable) is None
        # and model_fields_set contains the field
        if self.spam_marked_at is None and "spam_marked_at" in self.model_fields_set:
            _dict['spamMarkedAt'] = None

        # set to None if spam_marked_by (nullable) is None
        # and model_fields_set contains the field
        if self.spam_marked_by is None and "spam_marked_by" in self.model_fields_set:
            _dict['spamMarkedBy'] = None

        # set to None if approved_at (nullable) is None
        # and model_fields_set contains the field
        if self.approved_at is None and "approved_at" in self.model_fields_set:
            _dict['approvedAt'] = None

        # set to None if email_confirmed_at (nullable) is None
        # and model_fields_set contains the field
        if self.email_confirmed_at is None and "email_confirmed_at" in self.model_fields_set:
            _dict['emailConfirmedAt'] = None

        # set to None if credit_granted_at (nullable) is None
        # and model_fields_set contains the field
        if self.credit_granted_at is None and "credit_granted_at" in self.model_fields_set:
            _dict['creditGrantedAt'] = None

        # set to None if tier_pin (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pin is None and "tier_pin" in self.model_fields_set:
            _dict['tierPin'] = None

        # set to None if tier_pinned_at (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pinned_at is None and "tier_pinned_at" in self.model_fields_set:
            _dict['tierPinnedAt'] = None

        # set to None if tier_pinned_by (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pinned_by is None and "tier_pinned_by" in self.model_fields_set:
            _dict['tierPinnedBy'] = None

        # set to None if tier_pin_reason (nullable) is None
        # and model_fields_set contains the field
        if self.tier_pin_reason is None and "tier_pin_reason" in self.model_fields_set:
            _dict['tierPinReason'] = None

        # set to None if totp_secret (nullable) is None
        # and model_fields_set contains the field
        if self.totp_secret is None and "totp_secret" in self.model_fields_set:
            _dict['totpSecret'] = None

        # set to None if totp_secret_key_id (nullable) is None
        # and model_fields_set contains the field
        if self.totp_secret_key_id is None and "totp_secret_key_id" in self.model_fields_set:
            _dict['totpSecretKeyId'] = None

        # set to None if totp_confirmed_at (nullable) is None
        # and model_fields_set contains the field
        if self.totp_confirmed_at is None and "totp_confirmed_at" in self.model_fields_set:
            _dict['totpConfirmedAt'] = None

        # set to None if machine_for (nullable) is None
        # and model_fields_set contains the field
        if self.machine_for is None and "machine_for" in self.model_fields_set:
            _dict['machineFor'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deletedAt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        # set to None if avatar_photo_type (nullable) is None
        # and model_fields_set contains the field
        if self.avatar_photo_type is None and "avatar_photo_type" in self.model_fields_set:
            _dict['avatarPhotoType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "username": obj.get("username"),
            "displayName": obj.get("displayName"),
            "theme": obj.get("theme"),
            "locale": obj.get("locale"),
            "timezone": obj.get("timezone"),
            "password": obj.get("password"),
            "ldapDn": obj.get("ldapDn"),
            "avatarPhoto": UserAvatarPhoto.from_dict(obj["avatarPhoto"]) if obj.get("avatarPhoto") is not None else None,
            "roles": obj.get("roles"),
            "disabledAt": obj.get("disabledAt"),
            "spamMarkedAt": obj.get("spamMarkedAt"),
            "spamMarkedBy": User.from_dict(obj["spamMarkedBy"]) if obj.get("spamMarkedBy") is not None else None,
            "approvedAt": obj.get("approvedAt"),
            "emailConfirmedAt": obj.get("emailConfirmedAt"),
            "creditGrantedAt": obj.get("creditGrantedAt"),
            "tierPin": obj.get("tierPin"),
            "tierPinnedAt": obj.get("tierPinnedAt"),
            "tierPinnedBy": User.from_dict(obj["tierPinnedBy"]) if obj.get("tierPinnedBy") is not None else None,
            "tierPinReason": obj.get("tierPinReason"),
            "oauthIdentities": [OAuthIdentity.from_dict(_item) for _item in obj["oauthIdentities"]] if obj.get("oauthIdentities") is not None else None,
            "totpSecret": obj.get("totpSecret"),
            "totpSecretKeyId": obj.get("totpSecretKeyId"),
            "totpConfirmedAt": obj.get("totpConfirmedAt"),
            "recoveryCodes": [RecoveryCode.from_dict(_item) for _item in obj["recoveryCodes"]] if obj.get("recoveryCodes") is not None else None,
            "machineFor": obj.get("machineFor"),
            "id": obj.get("id"),
            "deletedAt": obj.get("deletedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "displayLabel": obj.get("displayLabel"),
            "machine": obj.get("machine"),
            "ldapManaged": obj.get("ldapManaged"),
            "avatarPhotoType": obj.get("avatarPhotoType"),
            "userIdentifier": obj.get("userIdentifier"),
            "grantedRoles": obj.get("grantedRoles"),
            "disabled": obj.get("disabled"),
            "spam": obj.get("spam"),
            "approved": obj.get("approved"),
            "emailConfirmed": obj.get("emailConfirmed"),
            "tierPinned": obj.get("tierPinned"),
            "totpEnabled": obj.get("totpEnabled"),
            "deleted": obj.get("deleted")
        })
        return _obj

from someones_computer_sdk.models.o_auth_identity import OAuthIdentity
from someones_computer_sdk.models.recovery_code import RecoveryCode
# TODO: Rewrite to not use raise_errors
User.model_rebuild(raise_errors=False)

