# coding: utf-8

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from someones_computer_sdk.models.user import User
from typing import Optional, Set
from typing_extensions import Self

class VariableVersion(BaseModel):
    """
    VariableVersion
    """ # noqa: E501
    variable: Optional[Variable] = None
    version: Optional[StrictInt] = None
    algo: Optional[StrictStr] = Field(default=None, description="Encryption algorithm identifier, e.g. \"xsalsa20poly1305\". Sensitive only.")
    key_id: Optional[StrictStr] = Field(default=None, description="Identifier of the key-encryption-key that wrapped this value. Sensitive only.", alias="keyId")
    nonce: Optional[StrictStr] = None
    ciphertext: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    created_by: Optional[User] = Field(default=None, alias="createdBy")
    id: Optional[StrictStr] = None
    encrypted: Optional[StrictStr] = Field(default=None, description="Populate an encrypted (sensitive) value.")
    plaintext: Optional[StrictStr] = Field(default=None, description="Populate a plaintext (non-sensitive) value.")
    __properties: ClassVar[List[str]] = ["variable", "version", "algo", "keyId", "nonce", "ciphertext", "createdAt", "createdBy", "id", "encrypted", "plaintext"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VariableVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "algo",
            "key_id",
            "nonce",
            "ciphertext",
            "created_at",
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of variable
        if self.variable:
            _dict['variable'] = self.variable.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # set to None if algo (nullable) is None
        # and model_fields_set contains the field
        if self.algo is None and "algo" in self.model_fields_set:
            _dict['algo'] = None

        # set to None if key_id (nullable) is None
        # and model_fields_set contains the field
        if self.key_id is None and "key_id" in self.model_fields_set:
            _dict['keyId'] = None

        # set to None if nonce (nullable) is None
        # and model_fields_set contains the field
        if self.nonce is None and "nonce" in self.model_fields_set:
            _dict['nonce'] = None

        # set to None if ciphertext (nullable) is None
        # and model_fields_set contains the field
        if self.ciphertext is None and "ciphertext" in self.model_fields_set:
            _dict['ciphertext'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['createdBy'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VariableVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "variable": Variable.from_dict(obj["variable"]) if obj.get("variable") is not None else None,
            "version": obj.get("version"),
            "algo": obj.get("algo"),
            "keyId": obj.get("keyId"),
            "nonce": obj.get("nonce"),
            "ciphertext": obj.get("ciphertext"),
            "createdAt": obj.get("createdAt"),
            "createdBy": User.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "id": obj.get("id"),
            "encrypted": obj.get("encrypted"),
            "plaintext": obj.get("plaintext")
        })
        return _obj

from someones_computer_sdk.models.variable import Variable
# TODO: Rewrite to not use raise_errors
VariableVersion.model_rebuild(raise_errors=False)

