# coding: utf-8

# flake8: noqa

"""
    someones.computer API

    JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AdoptionApprovalApi",
    "ApplicationApi",
    "CreditTransactionApi",
    "DeploymentApi",
    "DeploymentAccessGateApi",
    "ManagedServiceApi",
    "OrganizationApi",
    "ServiceBindingApi",
    "SwarmApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AdoptionApproval",
    "AdoptionApprovalAdoptionApprovalInput",
    "Application",
    "ApplicationJsonMergePatch",
    "BundleAdditionalContextInput",
    "BundleContextInput",
    "BundleForwardedImageInput",
    "BundleUploadTarget",
    "ConstraintViolation",
    "ConstraintViolationViolationsInner",
    "CreditTransaction",
    "CreditTransactionEngineMillis",
    "CreditTransactionUsageBytes",
    "Deployment",
    "DeploymentAccessGate",
    "DeploymentAccessGateJsonMergePatch",
    "DeploymentBundleUploadConfirmInput",
    "DeploymentBundleUploadConfirmOutput",
    "DeploymentBundleUploadDeclareInput",
    "DeploymentBundleUploadDeclareOutput",
    "DeploymentDeploymentEndpoint",
    "DeploymentJsonMergePatch",
    "DeploymentJsonMergePatchBuildContextsValueValue",
    "Error",
    "Failure",
    "Machine",
    "ManagedService",
    "ManagedServiceEngine",
    "ManagedServiceLastLoadMillis",
    "ManagedServiceManagedServiceInput",
    "ManagedServicePendingLoadMillis",
    "ManagedServiceQuotaBytes",
    "ManagedServiceUsageBytes",
    "Membership",
    "Organization",
    "OrganizationJsonMergePatch",
    "OrganizationSignal",
    "PortAllocation",
    "ProxmoxInstance",
    "Service",
    "ServiceBinding",
    "ServiceBindingServiceBindingInput",
    "ServiceCpuLimit",
    "ServiceCpuReservation",
    "ServiceHealthcheckValue",
    "ServiceMemLimit",
    "ServiceMemReservation",
    "ServicePortsInnerValue",
    "Swarm",
    "SwarmJsonMergePatch",
    "SwarmNode",
    "User",
]

# import apis into sdk package
from someones_computer_sdk.api.adoption_approval_api import AdoptionApprovalApi as AdoptionApprovalApi
from someones_computer_sdk.api.application_api import ApplicationApi as ApplicationApi
from someones_computer_sdk.api.credit_transaction_api import CreditTransactionApi as CreditTransactionApi
from someones_computer_sdk.api.deployment_api import DeploymentApi as DeploymentApi
from someones_computer_sdk.api.deployment_access_gate_api import DeploymentAccessGateApi as DeploymentAccessGateApi
from someones_computer_sdk.api.managed_service_api import ManagedServiceApi as ManagedServiceApi
from someones_computer_sdk.api.organization_api import OrganizationApi as OrganizationApi
from someones_computer_sdk.api.service_binding_api import ServiceBindingApi as ServiceBindingApi
from someones_computer_sdk.api.swarm_api import SwarmApi as SwarmApi

# import ApiClient
from someones_computer_sdk.api_response import ApiResponse as ApiResponse
from someones_computer_sdk.api_client import ApiClient as ApiClient
from someones_computer_sdk.configuration import Configuration as Configuration
from someones_computer_sdk.exceptions import OpenApiException as OpenApiException
from someones_computer_sdk.exceptions import ApiTypeError as ApiTypeError
from someones_computer_sdk.exceptions import ApiValueError as ApiValueError
from someones_computer_sdk.exceptions import ApiKeyError as ApiKeyError
from someones_computer_sdk.exceptions import ApiAttributeError as ApiAttributeError
from someones_computer_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from someones_computer_sdk.models.adoption_approval import AdoptionApproval as AdoptionApproval
from someones_computer_sdk.models.adoption_approval_adoption_approval_input import AdoptionApprovalAdoptionApprovalInput as AdoptionApprovalAdoptionApprovalInput
from someones_computer_sdk.models.application import Application as Application
from someones_computer_sdk.models.application_json_merge_patch import ApplicationJsonMergePatch as ApplicationJsonMergePatch
from someones_computer_sdk.models.bundle_additional_context_input import BundleAdditionalContextInput as BundleAdditionalContextInput
from someones_computer_sdk.models.bundle_context_input import BundleContextInput as BundleContextInput
from someones_computer_sdk.models.bundle_forwarded_image_input import BundleForwardedImageInput as BundleForwardedImageInput
from someones_computer_sdk.models.bundle_upload_target import BundleUploadTarget as BundleUploadTarget
from someones_computer_sdk.models.constraint_violation import ConstraintViolation as ConstraintViolation
from someones_computer_sdk.models.constraint_violation_violations_inner import ConstraintViolationViolationsInner as ConstraintViolationViolationsInner
from someones_computer_sdk.models.credit_transaction import CreditTransaction as CreditTransaction
from someones_computer_sdk.models.credit_transaction_engine_millis import CreditTransactionEngineMillis as CreditTransactionEngineMillis
from someones_computer_sdk.models.credit_transaction_usage_bytes import CreditTransactionUsageBytes as CreditTransactionUsageBytes
from someones_computer_sdk.models.deployment import Deployment as Deployment
from someones_computer_sdk.models.deployment_access_gate import DeploymentAccessGate as DeploymentAccessGate
from someones_computer_sdk.models.deployment_access_gate_json_merge_patch import DeploymentAccessGateJsonMergePatch as DeploymentAccessGateJsonMergePatch
from someones_computer_sdk.models.deployment_bundle_upload_confirm_input import DeploymentBundleUploadConfirmInput as DeploymentBundleUploadConfirmInput
from someones_computer_sdk.models.deployment_bundle_upload_confirm_output import DeploymentBundleUploadConfirmOutput as DeploymentBundleUploadConfirmOutput
from someones_computer_sdk.models.deployment_bundle_upload_declare_input import DeploymentBundleUploadDeclareInput as DeploymentBundleUploadDeclareInput
from someones_computer_sdk.models.deployment_bundle_upload_declare_output import DeploymentBundleUploadDeclareOutput as DeploymentBundleUploadDeclareOutput
from someones_computer_sdk.models.deployment_deployment_endpoint import DeploymentDeploymentEndpoint as DeploymentDeploymentEndpoint
from someones_computer_sdk.models.deployment_json_merge_patch import DeploymentJsonMergePatch as DeploymentJsonMergePatch
from someones_computer_sdk.models.deployment_json_merge_patch_build_contexts_value_value import DeploymentJsonMergePatchBuildContextsValueValue as DeploymentJsonMergePatchBuildContextsValueValue
from someones_computer_sdk.models.error import Error as Error
from someones_computer_sdk.models.failure import Failure as Failure
from someones_computer_sdk.models.machine import Machine as Machine
from someones_computer_sdk.models.managed_service import ManagedService as ManagedService
from someones_computer_sdk.models.managed_service_engine import ManagedServiceEngine as ManagedServiceEngine
from someones_computer_sdk.models.managed_service_last_load_millis import ManagedServiceLastLoadMillis as ManagedServiceLastLoadMillis
from someones_computer_sdk.models.managed_service_managed_service_input import ManagedServiceManagedServiceInput as ManagedServiceManagedServiceInput
from someones_computer_sdk.models.managed_service_pending_load_millis import ManagedServicePendingLoadMillis as ManagedServicePendingLoadMillis
from someones_computer_sdk.models.managed_service_quota_bytes import ManagedServiceQuotaBytes as ManagedServiceQuotaBytes
from someones_computer_sdk.models.managed_service_usage_bytes import ManagedServiceUsageBytes as ManagedServiceUsageBytes
from someones_computer_sdk.models.membership import Membership as Membership
from someones_computer_sdk.models.organization import Organization as Organization
from someones_computer_sdk.models.organization_json_merge_patch import OrganizationJsonMergePatch as OrganizationJsonMergePatch
from someones_computer_sdk.models.organization_signal import OrganizationSignal as OrganizationSignal
from someones_computer_sdk.models.port_allocation import PortAllocation as PortAllocation
from someones_computer_sdk.models.proxmox_instance import ProxmoxInstance as ProxmoxInstance
from someones_computer_sdk.models.service import Service as Service
from someones_computer_sdk.models.service_binding import ServiceBinding as ServiceBinding
from someones_computer_sdk.models.service_binding_service_binding_input import ServiceBindingServiceBindingInput as ServiceBindingServiceBindingInput
from someones_computer_sdk.models.service_cpu_limit import ServiceCpuLimit as ServiceCpuLimit
from someones_computer_sdk.models.service_cpu_reservation import ServiceCpuReservation as ServiceCpuReservation
from someones_computer_sdk.models.service_healthcheck_value import ServiceHealthcheckValue as ServiceHealthcheckValue
from someones_computer_sdk.models.service_mem_limit import ServiceMemLimit as ServiceMemLimit
from someones_computer_sdk.models.service_mem_reservation import ServiceMemReservation as ServiceMemReservation
from someones_computer_sdk.models.service_ports_inner_value import ServicePortsInnerValue as ServicePortsInnerValue
from someones_computer_sdk.models.swarm import Swarm as Swarm
from someones_computer_sdk.models.swarm_json_merge_patch import SwarmJsonMergePatch as SwarmJsonMergePatch
from someones_computer_sdk.models.swarm_node import SwarmNode as SwarmNode
from someones_computer_sdk.models.user import User as User

